### ISSUE TITLE
CountlyViewTracking

### ISSUE THREAD

**Issue by PyXXX** [Countly/countly-sdk-ios#105]
CountlyViewTracking

self.exceptionViewControllers =
        @[
          @"CLYInternalViewController",
          @"UINavigationController",
          @"UIAlertController",
          @"UIPageViewController",
          @"UITabBarController",
          @"UIReferenceLibraryViewController",
          @"UISplitViewController",
          @"UIInputViewController",
          @"UISearchController",
          @"UISearchContainerViewController",
          @"UIApplicationRotationFollowingController",
          @"_UIAlertControllerTextFieldViewController"
          ].mutableCopy;

Need to add @“_UIAlertControllerTextFieldViewController” ？？？
Are there other special circumstances?

**Comment by erkanyildiz** [comment]
What is this the problem? If you want to add another exception use `addExceptionForAutoViewTracking:`. Please see http://resources.count.ly/docs/countly-sdk-for-ios-and-os-x#section-view-tracking

And if you have any questions about how to use SDK, please ask it in support page https://community.count.ly
