### ISSUE TITLE
no plan update to AFNetworking ?

### ISSUE THREAD

**Issue by icoco** [Countly/countly-sdk-ios#106]

**Comment by erkanyildiz** [comment]
Can you explain?

**Comment by icoco** [comment]
I meaning  use AFNetworking but NSURLConnection post data to backend server

**Comment by erkanyildiz** [comment]
We do not use NSURLConnection, but we use NSURLSession and it is doing its job perfectly. 
Why do you think we should use a 3rd party dependency to handle simple network operations?
