### ISSUE TITLE
Countly APM with AFNetworking, the callback do not work

### ISSUE THREAD

**Issue by adntian** [Countly/countly-sdk-ios#107]
AFNetworking : 3.1.0
Countly : 16.12
iOS : 10.2 Simulator

when the GET and POST has callback, the block do not work, this is the test code

                {
                    AFHTTPSessionManager *manager = [AFHTTPSessionManager manager];
                    manager.responseSerializer.acceptableContentTypes = [NSSet setWithObjects:@"text/html",@"text/json",@"text/plain",@"text/javascript",@"application/json", nil];
                    NSLog(@"AFNetworking begin");
                    [manager GET:@"https://www.google.com" parameters:nil progress:nil success:^(NSURLSessionDataTask * _Nonnull task, id  _Nullable responseObject) {
                        NSLog(@"----------------------%@",responseObject);
                    } failure:^(NSURLSessionDataTask * _Nullable task, NSError * _Nonnull error) {
                        NSLog(@"_------------------------------------err-------%@", error);
                    }];
                }

the log

> 2017-02-21 14:07:41.902 CountlyTestApp-iOS[32445:4271426] Test: APM - testAFN
2017-02-21 14:07:41.910 CountlyTestApp-iOS[32445:4271426] AFNetworking begin
2017-02-21 14:07:41.914 CountlyTestApp-iOS[32445:4271426] taskId=1
2017-02-21 14:07:43.134 CountlyTestApp-iOS[32445:4271502] [Countly] APM log recorded:
Request <0x60000001d640> 
Request host: www.google.com 
Request path:  
Start Time: 1487657261.911667 
End Time: 1487657263.133930 
Time Elapsed: 1.222263 
HTTP Status Code: 200 
Sent Data Size: 106 
Received Data Size: 10645 
Connection Type: 1 
Request Successful: 1

 
paste the AFNetworking source code

> - (NSURLSessionDataTask *)dataTaskWithRequest:(NSURLRequest *)request
                               uploadProgress:(nullable void (^)(NSProgress *uploadProgress)) uploadProgressBlock
                             downloadProgress:(nullable void (^)(NSProgress *downloadProgress)) downloadProgressBlock
                            completionHandler:(nullable void (^)(NSURLResponse *response, id _Nullable responseObject,  NSError * _Nullable error))completionHandler {

    __block NSURLSessionDataTask *dataTask = nil;
    url_session_manager_create_task_safely(^{
        dataTask = [self.session dataTaskWithRequest:request];
    });

    [self addDelegateForDataTask:dataTask uploadProgress:uploadProgressBlock downloadProgress:downloadProgressBlock completionHandler:completionHandler];

    return dataTask;
}

Are they has some conflict ?

**Comment by erkanyildiz** [comment]
Yes.

https://github.com/Countly/countly-sdk-ios/issues/82
