### ISSUE TITLE
Feature Request: Disable Push Support

### ISSUE THREAD

**Issue by tternes** [Countly/countly-sdk-ios#108]
I've recently integrated the latest version of the Countly SDK into an iOS app I'm building. My application doesn't use notifications (so it doesn't include a push notification entitlement). However, when uploading a build to iTunes Connect, Apple's symbol checking detects push API usage without proper entitlements.

To appease the warning from iTunes Connect, I've simply removed `CountlyPushNotifications.m` from my target and commented out the other references in the SDK. However, I'd much prefer the ability to opt out of the functionality without having to modify the SDK. Something as simple as a preprocessor flag (`COUNTLY_DISABLE_PUSH=1` or similar) would be great.

Is this capability something that may be added in the future? I'd be glad to explore this or other options if you'd be interested in a PR.

**Comment by erkanyildiz** [comment]
Hi,

Actually it is just a warning. A kind of reminder. Nothing serious.
So, if your app does not use push notification, it is OK.
You **don't need** to remove push related code from the SDK. 
You **don't need** to re-upload a new build. 

You can see it in the warning message from iTunes Connect also:
`If your app does not use the Apple Push Notification service, no action is required.`

Thanks.

**Comment by ArnRdy** [comment]
The email that I received when I uploaded the build including Countly without any notifications configuration, says the app need entitlements or push notifications capability is necessary while the app does not need any notification services. 

![Screenshot 2019-07-14 at 8 09 57 PM](https://user-images.githubusercontent.com/1443802/61185156-78d22a80-a673-11e9-9cd8-bbb4c3f8556c.png)

Is it still okay to proceed with the review process?

**Comment by ddaddy** [comment]
Yes, it’s safe to ignore the warning. It’s simply telling you that they’ve detected notification code in your app without you actually setting up notifications.
