### ISSUE TITLE
Apple IDFA Approval

### ISSUE THREAD

**Issue by benfrye** [Countly/countly-sdk-ios#110]
When submitting an app to the app store, Apple scans the app, and if any code is referencing the IDFA, it flags the app:

`“Your app is using the Advertising Identifier (IDFA). You must either provide details about the IDFA usage or remove it from the app and submit your binary again.”`

This happens even if the codepath is not used (as it is in our case). According to Apple, you're only allowed to utilize this identifier for one of the below purposes:

* Serve advertisements within the app
* Attribute this app installation to a previously served advertisement
* Attribute an action taken within this app to a previously served advertisement

Have you all run into this with other apps before, and if so, what is your supported solution for handling? I see that you have deprecated using the IDFA, implying that you're aware of this limitation. In the meantime we have simply gone into the code, and manually removed usage of the IDFA, but are looking for a more maintainable solution that doesn't involve changing your code. A proposed solution would be to provide IDFA as an optional feature, similar to [how Google handles this](https://developers.google.com/analytics/devguides/collection/ios/v3/optional-features), so that developers could choose to not include the feature. Given that you've deprecated this feature, I'm not sure if that sounds like the best route for your team, though, which may be to simply remove references to IDFA in total.

**Comment by erkanyildiz** [comment]
Hi,
We are planning to completely remove IDFA and OpenUDID support in the next major release.
We are still keeping them to give a chance to some legacy SDK users for device ID switching.

For now you can our notice about it: 
http://resources.count.ly/docs/countly-sdk-for-ios-and-os-x#section-itunesconnect-idfa-warning
