### ISSUE TITLE
how can i fix such crash log from countly

### ISSUE THREAD

**Issue by FrankCYQ** [Countly/countly-sdk-ios#111]
The crash title is "*** +[NSLAYOUTCONSTRAINT CONSTRAINTWITHITEM:ATTRIBUTE:RELATEDBY:TOITEM:ATTRIBUTE"

Detail info like this
CoreFoundation                      0x0000000183532dc8 <redacted> + 148
libobjc.A.dylib                     0x0000000182b97f80 objc_exception_throw + 56
CoreFoundation                      0x0000000183532cf8 <redacted> + 0
Foundation                          0x0000000183feba64 <redacted> + 208
Foundation                          0x0000000183e6cc3c <redacted> + 304
Athena_Distribution                 0x000000010035b474 Athena_Distribution + 2503796
Athena_Distribution                 0x0000000100358d78 Athena_Distribution + 2493816
Athena_Distribution                 0x000000010035e9f8 Athena_Distribution + 2517496
Athena_Distribution                 0x000000010015eed0 Athena_Distribution + 421584
UIKit                               0x00000001886901e4 <redacted> + 656
QuartzCore                          0x000000018601e98c <redacted> + 148
QuartzCore                          0x00000001860195c8 <redacted> + 292
QuartzCore                          0x0000000186019488 <redacted> + 32
QuartzCore                          0x0000000186018ab8 <redacted> + 252
QuartzCore                          0x0000000186018818 <redacted> + 500
QuartzCore                          0x0000000186011ddc <redacted> + 80
CoreFoundation                      0x00000001834e8728 <redacted> + 32
CoreFoundation                      0x00000001834e64cc <redacted> + 372
CoreFoundation                      0x00000001834e68fc <redacted> + 928
CoreFoundation                      0x0000000183410c50 CFRunLoopRunSpecific + 384
GraphicsServices                    0x0000000184cf8088 GSEventRunModal + 180
UIKit                               0x00000001886fe088 UIApplicationMain + 204
Athena_Distribution                 0x0000000100164c8c Athena_Distribution + 445580
libdyld.dylib                       0x0000000182fae8b8 <redacted> + 

![4c2873e3a459e89c5406035d43f79c4b](https://user-images.githubusercontent.com/5100958/29614775-1aa772f8-883e-11e7-8800-ce931af07e75.jpg)

**Comment by erkanyildiz** [comment]
This has nothing to do with the SDK. 
You should send your questions to Countly support, not create issue here.
