### ISSUE TITLE
Suspend and resume methods are now private for iOS

### ISSUE THREAD

**Issue by michalcichon** [Countly/countly-sdk-ios#114]
These two methods are available on watchOS only. See the Countly.h fragment below:

```
#if TARGET_OS_WATCH
/**
 * Suspends Countly, adds recorded events to request queue and ends current session.
 * @discussion This method needs to be called manually only on @c watchOS, on other platforms it will be called automatically.
 */
- (void)suspend;

/**
 * Resumes Countly, begins a new session after app comes to foreground.
 * @discussion This method needs to be called manually only on @c watchOS, on other platforms it will be called automatically.
 */
- (void)resume;
```

If we want to suspend the session for a while, then with the newest version, we need to set the `manualSessionHandling` flag and manage the sessions completely manually.

In my case I want to stop sending updates for some subset of users but without these two methods I cannot do it easily.

Will you consider to bring those methods back to be public or extend somehow the manual session handling to not force developer to manage also session updates but only starting/ending sessions?

**Comment by erkanyildiz** [comment]
Yes, they are intended to be used on watchOS since the beginning. 
And we made them private on all platforms other than watchOS, because we want to keep the interface as simple as possible.

What about creating a category to expose them for your use case:
```
//  Countly+SuspendResume.h

#import "Countly.h"

@interface Countly (SuspendResume)
- (void)suspend;
- (void)resume;
@end
```

With this you won't need to edit SDK source, and can use suspend/resume methods as you need.

**Comment by michalcichon** [comment]
Thanks for clearing this out. I was thinking about creating a category, but to be honest I don't like this solution. A category has no access to private methods, so instead of declaring `suspend` and `resume` methods here I should declare my own methods and try to call them by `performSelector`. Otherwise I would get warnings that I would like to avoid.

```
Method definition for 'resume' not found
Method definition for 'suspend' not found
```

So the solution would be something like this:

```objc
#import "Countly.h"

@interface Countly (SuspendResume)

- (void)suspendInPrivateMethod;
- (void)resumeInPrivateMethod;

@end
```

```objc
#import "Countly+SuspendResume.h"
#import "Countly.h"

@implementation Countly (SuspendResume)

- (void)suspendInPrivateMethod {
    if ([self respondsToSelector:@selector(suspend)]) {
        [self performSelector:@selector(suspend) withObject:nil];
    }
}

- (void)resumeInPrivateMethod {
    if ([self respondsToSelector:@selector(resume)]) {
        [self performSelector:@selector(resume) withObject:nil];
    }
}

@end
```

This is also fragile because of fact if you change the internal implementation of Countly then I could have no access to the `suspend` and `resume` methods (for example if they no longer exist).

I could go with that as a temporary solution but having some "official" solution would be much better.

**Comment by erkanyildiz** [comment]
Hmm. You can just delete the .m file. And those warnings you want to avoid should be gone.

**Comment by michalcichon** [comment]
OK, that should work as I will have only declarations in the category. You're right. But anyways it is dependent on internal implementation of your class so I can accept it as a temporary solution. Thanks for your help.

**Comment by michalcichon** [comment]
If there are no plans to support suspend/resume from the library’s public API then I think I will create an independent pod to extend Countly to cover this functionality based on the current API. In this case please close this issue.

**Comment by erkanyildiz** [comment]
You are welcome.
