### ISSUE TITLE
can not parse sigsegv

### ISSUE THREAD

**Issue by depthlove** [Countly/countly-sdk-ios#119]
（1）iOS app call the third sdk

（2）the third sdk occurs c/c++ null point crash

   (3) the ce countly server can not parse sigsegv

   (4) the bugly toolbox can parse sigsegv normally

![7a1f7459-83d3-40de-8a6c-b1d09787de1b](https://user-images.githubusercontent.com/6168251/36822420-edb721be-1d32-11e8-8880-ea5695551a5b.jpeg)

**Comment by erkanyildiz** [comment]
Currently, Countly Server does not support system libraries (and 3rd party libraries) for symbolication.
