### ISSUE TITLE
MacOS Crash not working

### ISSUE THREAD

**Issue by joubin** [Countly/countly-sdk-ios#127]
As the title says, I am trying to test crashes and capture them using Countly.

I am simply doing `kill(getpid(), SIGABRT)` right after I enable Countly like so:

`
        let config: CountlyConfig = CountlyConfig()

        config.appKey = Utils.cloudlyAPIKey

        config.host = Utils.cloudlyURL

        config.enableDebug = true

        Countly.sharedInstance().start(with: config)
`

Please note that I was not able to add `CLYCrashReporting` to the features since I get an error that it does not exist. I was able to find the CLYCrashReportingConsent, but I don't think that is correct. 
### Expected Behavior

I would expect that much like the iOS example code where the `kill` code registers a crash event in the Countly Server Console, that the MacOS version does the same. 

### Current Behavior

Nothing is logged in the crash events 

### Steps to Reproduce (for bugs)

1. The code is provided. I just run the code. 
2. I know that it crashes because I can see the SIGINT in the Console.app 

### Your Environment

* Countly iOS SDK version
* Your iOS version
* Any changes you have made to this SDK

**Comment by erkanyildiz** [comment]
Crash Reporting feature is not supported on macOS yet.

**Comment by martindufort** [comment]
Is this feature under development now? For our product, we don't want to track MacOS crashes with a separate tool. Thanks

**Comment by erkanyildiz** [comment]
Yes, it will be a part of the new release this week.
