### ISSUE TITLE
Signalhandler does not respect new Xamarin.ios default handlers

### ISSUE THREAD

**Issue by frankHarmann** [Countly/countly-sdk-ios#128]
Current signal handler implementation overrides Mono's default handler, resulting in SIGSEGV aborts on NullReferenceExceptions.

See (also for recommended fix):
https://stackoverflow.com/questions/14499334/how-to-prevent-ios-crash-reporters-from-crashing-monotouch-apps/14499336#14499336

**Comment by erkanyildiz** [comment]
This seems to be Xamarin specific problem, not Countly.

Thanks.
