### ISSUE TITLE
Enhancement: chrashLog

### ISSUE THREAD

**Issue by frankHarmann** [Countly/countly-sdk-ios#129]
We are using the "log"-Method of the CrashReporter to provide some more background on what happened before the app crashes (f.e. by tracing method calls).
In case of a crash we only want the last x added logs to be transfered to the server, but unfortunately the crashLog variable used internally is not providing some "rotation" or size limit and can't even be resetted (as it is private). We currently have to use some kind of workaround which resets the variable by stopping/starting the CrashReporter(the only way to reset the variable), when we reached the limit of logs we want to store.

### Expected Behavior
a )Provide a way to configure the crashLog variable to store only the last x calls to the log-method (like a rotating log) [prefered solution].

or 

b) Provide a method to clear the crashLog Variable.

Thanks

**Comment by erkanyildiz** [comment]
This already implemented in my fork and it will be part of the main repo soon.
https://github.com/erkanyildiz/countly-sdk-ios/commit/84e5a191577166e1f04f2b0a63060535e07c5bbf

Thanks.
