### ISSUE TITLE
Please provide way to customize session configuration 

### ISSUE THREAD

**Issue by dKasabwala** [Countly/countly-sdk-ios#134]
countly should have a way to customize configuration , so someone can use it diffrent header setup for session request and can use with diffrent proxy setup

**Comment by erkanyildiz** [comment]
Definitely a great contribution. I will merge it with little bit modification + documentation, after the next release.

**Comment by erkanyildiz** [comment]
https://github.com/Countly/countly-sdk-ios/pull/133#issuecomment-520245901
