### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by clawoo** [Countly/countly-sdk-ios#137]
### Expected Behavior
Library should build using carthage

### Current Behavior
In the attached pull request I added Carthage support. Reasoning: the advantage of using a standalone framework file is faster build times. This is of course not an issue on smaller projects, but for larger projects I like to keep external libraries as prebuilt frameworks in order to squeeze any second out of the build time.

As per Carthage documentation, running `carthage build --no-skip-current` on a project with a shared scheme should complete successfully.

### Solution
Added a project file that allows Carthage to build the library as a framework. The deployment target is set to 8.0 and the bundle identifier to ly.count.Countly. Signing is left to manual with no profiles selected. The only public headers are 'Countly.h', 'CountlyUserDetails.h', 'CountlyConfig.h'.

I created a pull request here: https://github.com/Countly/countly-sdk-ios/pull/136

**Comment by erkanyildiz** [comment]
Thanks. I will update bundle identifier in project file and version number in Info.plist.
