### ISSUE TITLE
COUNTLY_EXCLUDE_IDFA doesn't work

### ISSUE THREAD

**Issue by wjthieme** [Countly/countly-sdk-ios#139]
I'm trying to exclude the IDFA from my final binary using Countly so I can answer no to the Export Compliance question "Does your app use the IDFA?".

Adding ```COUNTLY_EXCLUDE_IDFA=1``` to ```Build Settings > Preprocessor Macros``` as mentioned [here](https://resources.count.ly/docs/countly-sdk-for-ios-and-os-x#section-app-store-connect-idfa-warning) doesn't work.

I've narrowed it down to ```#ifndef``` not behaving as expected. I've injected this piece of code in the startupWithConfig method in Countly.m

```
#ifndef COUNTLY_EXCLUDE_IDFA
    printf("!EXCLUDED\n");
#else
    printf("EXCLUDED\n");
#endif
```

### Expected Behavior
If I add ```COUNTLY_EXCLUDE_IDFA=1``` as a ```Preprocessor Macro``` I expect the block inside ```#ifndef``` not to be executed. I expect the above code to print ```EXCLUDED``` but it does print ```!EXCLUDED```.

### Current Behavior
Right now it doesn't matter if I add ```COUNTLY_EXCLUDE_IDFA=1``` to the ```Preprocessor Macros``` or not. The above code will always print ```!EXCLUDED```.

### Possible Fix
I've played around with ```Preprocessor Macros``` and the only thing that seems to work is:

```
#if COUNTLY_EXCLUDE_IDFA
    printf("EXCLUDED\n");
#else
   printf("!EXCLUDED\n");
#endif
```

### Your Environment
* Countly 18.08 & 19.02
* iOS 12.0
* Swift 4.2 & 5

**Comment by erkanyildiz** [comment]
It works. Please make sure you properly add `COUNTLY_EXCLUDE_IDFA` to correct target and build configuration.
