### ISSUE TITLE
onTimer seems to never get called

### ISSUE THREAD

**Issue by mt-rpranata** [Countly/countly-sdk-ios#145]
### Expected Behavior

Given [a config object](https://github.com/Countly/countly-sdk-ios/blob/19.02/CountlyConfig.h) to [initialise countly](https://github.com/Countly/countly-sdk-ios/blob/19.02/Countly.m#L58),

When a small number of event (1) is logged through Countly SDK 

It should eventually be sent to the server when `config.updateSessionPeriod` has elapsed (default 60s), even when the number of events are below the threshold `config.eventSendThreshold` (default 10)

### Current Behavior

Seems like the [`onTimer`](https://github.com/Countly/countly-sdk-ios/blob/19.02/Countly.m#L237) method that is called when the timer fires to clear up the events currently in the cache are never fired. This caused the events to stay in the cache until the `config.eventSendThreshold` is met.

### Steps to Reproduce (for bugs)

1. Start the countly instance using 
`[[Countly sharedInstance] startWithConfig:config]`

2. Log an event using 
`[[Countly sharedInstance] recordEvent:@"foobar"]`

3. Wait for the `config.updateSessionPeriod` to elapse (by default 60 second)

4. Even when it elapsed; the timer seems to never fire and the event is never being sent to the server

### More Description

In the `startWithConfig:` method [on Countly.m](https://github.com/Countly/countly-sdk-ios/blob/19.02/Countly.m#L144-L145), the timer object is being initialised and added to the run loop with configuration like below

```
timer = [NSTimer scheduledTimerWithTimeInterval:config.updateSessionPeriod target:self selector:@selector(onTimer:) userInfo:nil repeats:YES];
[NSRunLoop.mainRunLoop addTimer:timer forMode:NSRunLoopCommonModes];
```

### Your Environment

| Environment        | Values           |
| ------------- |:-------------:|
| Countly iOS SDK version     |  **v19.02**|
| Your iOS version     | 12.2      | 

* Any changes you have made to this SDK: None

**Comment by mt-rpranata** [comment]
Just realised that the `timer` is initialised with the `scheduledTimerWithTimeInterval:config` method. The documentation of the [`scheduledTimerWithTimeInterval`](https://developer.apple.com/documentation/foundation/nstimer/1412416-scheduledtimerwithtimeinterval?language=objc) indicates that it is automatically added on the current run loop

> Creates a timer and schedules it on the current run loop in the default mode.

However, the line after initialisation, the timer [is being added into the `mainRunLoop` manually](https://github.com/Countly/countly-sdk-ios/blob/19.02/Countly.m#L144-L145)
```
[NSRunLoop.mainRunLoop addTimer:timer forMode:NSRunLoopCommonModes];
```

I think for correctness, if we want to specifically add the timer to the `mainRunLoop`, we should be using the timer using [`timerWithTimeInterval:target:selector:userInfo:repeats:` method](https://developer.apple.com/documentation/foundation/nstimer/1408356-timerwithtimeinterval?language=objc)

**Comment by erkanyildiz** [comment]
Hi,

Just please make sure you start Countly on main thread. It will work fine.

> Creates a timer and schedules it on the current run loop in the default mode.

Yes, at that point current run loop is supposed to be main thread's run loop.

> is being added into the mainRunLoop manually

Yes, this is for adding the timer for `NSRunLoopCommonModes`, so the timer won't not be blocked during user interactions like scrolling where run loop switches to `NSEventTrackingRunLoopMode`.

> if we want to specifically add the timer to the mainRunLoop

Actually, the point of that call is not to add it to `mainRunLoop`, as it is already there when Countly is started on main thread. Point is adding it for `NSRunLoopCommonModes` to avoid problems I explained above.

And it is OK to add a timer for more than one mode. Especially if it is `NSRunLoopCommonModes` which includes `NSDefaultRunLoopMode` already.

> using `timerWithTimeInterval:target:selector:userInfo:repeats:`
Yes, it is also OK. I may consider merging your change.

Thank you.

**Comment by mt-rpranata** [comment]
@erkanyildiz Yes; I am not questioning why was the timer added manually to the run loop. 

I still think that using the `timerWithTimeInterval:target:selector:userInfo:repeats:` API to initialise the timer object is better because the object returned is intended to be added to the run loop.

The object returned by [`scheduledTimerWithTimeInterval:`](https://developer.apple.com/documentation/foundation/nstimer/1412416-scheduledtimerwithtimeinterval?language=objc) has already been aded to the current run loop per Apple Documentation.

> Creates a timer and schedules it on the current run loop in the default mode.

If you want to create a timer object and add it to a run loop yourself, you need to use the [`timerWithTimeInterval:target:selector:userInfo:repeats:`](https://developer.apple.com/documentation/foundation/nstimer/1408356-timerwithtimeinterval?language=objc) API

I don't understand the reluctance to call the correct API

**Comment by erkanyildiz** [comment]
Hi again, 

Naming it `the correct` is a little bit over-stating, as it does not have any problems with the current implementation when used as supposed to, and the end result should be the same for both API calls, as I explained above. 

But, definitely your suggestion is a better one. 

That's why I said we will consider merging it. 
By the way, my comment is rendered as a part of the quote of your previous message, it may be difficult to notice that.

And, the issue you were having is related to `not starting Countly on main thread`, and I guess this change is not related to it.

One more point I would like to mention: in some cases, we may close merge requests due to styling/naming issues or other implementation details, and implement the suggested changes ourselves, then mention original contributors' name both in commit message and release notes. Sorry for not explaining it clearly. 

We are always open for contributions as we have been all along, both on SDKs side and server side. 
But definitely we will try to communicate better.

Thanks again.

**Comment by mt-rpranata** [comment]
@erkanyildiz Nope. its not understating. Just because it works does not mean it's right. The way how the API is being used at the moment is not at all a reflection of how the API is intended to be used, even the documentation stated that. 

> And, the issue you were having is related to not starting Countly on main thread, and I guess this change is not related to it.

Not directly but indirectly. If this change is applied, everything works as expected even if I am not calling it from the main thread. However, because this method is not intended to be called from a non-main thread, I understand that it might cause some issue somewhere else. (I have changed it to call your API on the main thread).

Thank you for clearing it up. The idea of an open source is to always welcoming contributions from third party, if not, might as well make it a close source. If there is anything you would like to be done on the code, you could just comment in the pull request and we'll make the changes that satisfy your code styling or naming.
