### ISSUE TITLE
appKey update requires app reinstall 

### ISSUE THREAD

**Issue by joshhopkins** [Countly/countly-sdk-ios#148]
Moved Countly to another instance, replaced new `appKey` within `CountlyConfig` and kept on receiving datapoint to "Deleted app". 

### Expected Behavior
Rebuilding app updates the `appKey`.

### Current Behavior
After multiple reinstalls of Countly server, it turned out that the issues is with the SDK – it appears that rebuilding the app with the new `appKey` isn't working and requires the user to uninstall the app first.

### Steps to Reproduce (for bugs)
1. Install Countly server and create app
2. Buil iOS app with `appKey` and build (everything works)
3. Setup 2nd Countly server
4. Rebuild iOS app with 2nd `appKey` (datapoint are now sent to "Deleted app".)

### Your Environment

* Countly iOS SDK version: 19.08
* Your iOS version: 12.4

**Comment by erkanyildiz** [comment]
Hello, 

Are we talking requests stored on the device? 
If so, they will be stored with `app_key` and `device_id`, and they will be send sent to server as is. Changing the app key on initial configuration will not affect them. Only the new requests will be using the new app key.

**Comment by joshhopkins** [comment]
In this case it was new requests. Update `app_key` > rebuild app > test application > data points still sent to "Deleted App".

**Comment by erkanyildiz** [comment]
`appKey` on initial configuration is not persistently stored anywhere. 
It is used `as is` whatever specified on initial configuration.

Can you please check your app building settings again.

**Comment by erkanyildiz** [comment]
Closing for now.
If you have any updates, please feel free to ask for re-opening.

**Comment by joshhopkins** [comment]
Odd. Build settings seem fine. Haven't had the issue since, but will keep an eye on it.
