### ISSUE TITLE
hello, can I set the source from sdk?

### ISSUE THREAD

**Issue by zfavourite99** [Countly/countly-sdk-ios#149]
I found an attribute named 'source' from countly web page. can I set it's value manual?

![image](https://user-images.githubusercontent.com/2630290/64008598-fc26dd00-cb48-11e9-8dd3-7ba7aba72437.png)

**Comment by erkanyildiz** [comment]
Hi,

There is no `source` attribute on Countly iOS SDK, but judging from the screenshot you are talking about `platform` maybe.

No, it is not possible to set it externally, as it is hardcoded for each OS.
But of course, you can edit SDK source as you need.
