### ISSUE TITLE
Mac Catalyst support

### ISSUE THREAD

**Issue by telipskiy** [Countly/countly-sdk-ios#151]
When trying to port an iOS app to the Mac via Catalyst, Countly pod fails to compile because it is relying on a deprecated API (EAGLContext) that was not ported for the Mac via Catalyst.

file CountlyDeviceInfo.m line 399

```
#if TARGET_OS_IOS
    EAGLContext *aContext;

    aContext = [EAGLContext.alloc initWithAPI:kEAGLRenderingAPIOpenGLES3];
    if (aContext)
        return @"3.0";

    aContext = [EAGLContext.alloc initWithAPI:kEAGLRenderingAPIOpenGLES2];
    if (aContext)
        return @"2.0";

    return @"1.0";
#else
    return @"1.0";
#endif
```

**Comment by telipskiy** [comment]
Hey, there is the smallest fix that we can imagine, but still no reaction

```
+ (NSString *)OpenGLESversion
{
#if !TARGET_OS_UIKITFORMAC && TARGET_OS_IOS
    EAGLContext *aContext;

    aContext = [EAGLContext.alloc initWithAPI:kEAGLRenderingAPIOpenGLES3];
    if (aContext)
        return @"3.0";

    aContext = [EAGLContext.alloc initWithAPI:kEAGLRenderingAPIOpenGLES2];
    if (aContext)
        return @"2.0";

    return @"1.0";
#else
    return @"1.0";
#endif
}
```

**Comment by erkanyildiz** [comment]
Hi @telipskiy 

Thank you very much for reporting this.

We will discard OpenGL ES version info altogether. So, it will not be an issue anymore :)

**Comment by telipskiy** [comment]
Hi, thanks a lot :)

**Comment by erkanyildiz** [comment]
Here it is:

https://github.com/erkanyildiz/countly-sdk-ios/commit/5d014118addfa642cfda3cb4f33e038fe27ee7a1

It will be merged into main repo on next release.
