### ISSUE TITLE
dSYM upload script custom path argument

### ISSUE THREAD

**Issue by armcknight** [Countly/countly-sdk-ios#152]
We need to upload dSYMs for exported IPAs and for apps recompiled from BitCode. Invoking the script only from the Run Script Build Phase is too early to do this, as the dSYMs that match the binary UUIDs from either IPA export or BitCode recompilation are different from the binary dSYM of the originally compiled app target available during that build phase. 

Ultimately, we were not able to receive symbolicated crash reports due to this UUID mismatch. Once we were able to locate the matching dSYM, providing the path to it to a modified version of the upload script set us up to successfully symbolicate a test crash from our app.

**Comment by erkanyildiz** [comment]
Please see 

https://github.com/Countly/countly-sdk-ios/pull/153

and

https://github.com/erkanyildiz/countly-sdk-ios/commit/b637516d553677fdf84ab26281484ba3f5a6d243
