### ISSUE TITLE
Sending deeplink through notification can crash iOS app

### ISSUE THREAD

**Issue by rudolfkopriva** [Countly/countly-sdk-ios#154]
When user taps on notification, it should process the deeeplink without crashing the app.

### Current Behavior
Push notification with deeplink can freeze the app for 10 seconds, which causes watchdog violation and crash.

### Possible Solution
What seems to help is to call openURL from global queue instead of main queue.

### More Description
Application is running in foreground on iOS 13.2.2 device. Push notification is received with deeplink URL. User taps on the notification. The following code in CountlyPushNotifications.m is called:

`[UIApplication.sharedApplication openURL:[NSURL URLWithString:URLString]];`

Sometimes the call freezes for 10 seconds, which is causing a watchdog violation and crash. If debugging the app doesn't crash, but the timeout is still present.
This appears to be [known issue](https://stackoverflow.com/questions/19356488/openurl-freezes-app-for-over-10-seconds) and I see Countly is delaying the call to avoid this issue, however the delayed call doesn't always help. What seems to help is to move the call to background thread.

### Environment
iPhone X iOS 13.2.2
Countly 19.08

**Comment by erkanyildiz** [comment]
Hi @rudolfkopriva 

Back then the solution for the issue you shared was forcing the call on main thread.
And I see that you say it does not always work. (probably due to iOS13?)

> What seems to help is to move the call to background thread.

As this is the exact opposite of previously valid current solution, can you elaborate this little bit more. 

Thank you very much.

**Comment by rudolfkopriva** [comment]
Hi @erkanyildiz, I cannot reproduce it any more. I used https://github.com/Countly/countly-sample-ios, sent test push notification with deeplink URL and it is working correctly. Perhaps it was fixed in iOS.

**Comment by erkanyildiz** [comment]
Most probably.
Thanks.
