### ISSUE TITLE
"COUNTLY_EXCLUDE_IDFA=1" This Preprocessor Macro does not work. 

### ISSUE THREAD

**Issue by duanchao505** [Countly/countly-sdk-ios#157]
![image](https://user-images.githubusercontent.com/17867957/78954889-19288300-7b10-11ea-92b1-85a57962124f.png)

![image](https://user-images.githubusercontent.com/17867957/78954941-3b220580-7b10-11ea-8a73-b402bf57cd77.png)

when I use this Preprocessor Macro ("COUNTLY_EXCLUDE_IDFA=1") which the countly document suggest(https://support.count.ly/hc/en-us/articles/360037753511-iOS-watchOS-tvOS-macOS), itunes can still detect that the application package contains IDFA

pod 'Countly', '19.02'

**Comment by erkanyildiz** [comment]
Please make sure you read this part of the documentation:

> If you are adding Countly iOS SDK source files directly to your project, make sure the flag is added to your app target. If you are adding it as a framework, make sure the flag is added to framework target.
