### ISSUE TITLE
Swift Package Manager

### ISSUE THREAD

**Issue by lhunath** [Countly/countly-sdk-ios#161]
Official Apple iOS dependency management is moving to the Swift Package Manager, which has built-in support starting Xcode 11.

See:
https://swift.org/package-manager/

### Expected Behavior
Xcode -> File -> Swift Packages -> Add Package Dependency...
Enter URL: https://github.com/Countly/countly-sdk-ios.git
Countly support is added to your target.

### Current Behavior
```
: https://github.com/Countly/countly-sdk-ios.git has no Package.swift manifest for version 16.6.4
```

### Possible Solution
Add a basic `Package.swift` manifest to the repository root.

**Comment by ismailkilic** [comment]
Yes, We are still waiting SPM like you. We hope we will get it as soon as possible

**Comment by erkanyildiz** [comment]
Hello, 
It will be added on the next major release.

**Comment by drademacher** [comment]
@erkanyildiz when is the next major release to be expected? This year? Early 2021?

**Comment by SocialKitLtd** [comment]
Any news about that? We want to use your system but currently only working with SPM.

**Comment by erkanyildiz** [comment]
> @erkanyildiz when is the next major release to be expected? This year? Early 2021?

This month. But there is a possibility that SPM support won't be a part of this release. In that case, SPM support will be added as a minor release.

**Comment by erkanyildiz** [comment]
https://github.com/erkanyildiz/countly-sdk-ios/commit/ed852b361cb6011fbc44078019b00cc6e76ef9f7

Soon it will be merged to main repo.
