### ISSUE TITLE
Allow newer minor/patch revisions to PLCrashReporter to coexist with Countly CocoaPod

### ISSUE THREAD

**Issue by armcknight** [Countly/countly-sdk-ios#164]
I can't upgrade to the latest version of PLCrashReporter ([1.7.1](https://github.com/microsoft/plcrashreporter/releases/tag/1.7.1)) while also depending on Countly via CocoaPods. This is because Countly's dependency on PLCrashReporter is pinned to 1.5.1: https://github.com/Countly/countly-sdk-ios/blob/a982db6cca5978f71328381d509428dd1303278d/Countly.podspec#L33

### Expected Behavior
CocoaPods is able to resolve my dependency tree to use Countly and PLCrashReporter if I want to use PLCrashReporter releases later than 1.5.1.

### Current Behavior
CocoaPods can't link PLCrashReporter 1.7.1, and forces me to downgrade back to 1.5.1.

### Possible Solution
Two options:

1. Upgrade the dependency to 1.7.1
1. Use the optimistic operator to allow any PLCrashReporter version that doesn't introduce a breaking change that would break your build: `~> 1`

### Steps to Reproduce (for bugs)
Given a Podfile:
```ruby
target 'a' do
  pod 'PLCrashReporter', '1.7.1'
end

target 'b' do
  pod 'Countly'
  pod 'Countly/PL'
end
```

1. try to `pod install`
 Expected output:
```
Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "PLCrashReporter":
  In Podfile:
    Countly/PL was resolved to 20.04.2, which depends on
      PLCrashReporter (= 1.5.1)

    PLCrashReporter (= 1.7.1)

Specs satisfying the `PLCrashReporter (= 1.7.1), PLCrashReporter (= 1.5.1)` dependency were found, but they required a higher minimum deployment target.
```

**Comment by erkanyildiz** [comment]
Hello again Andrew,

This should be taking care of it:

https://github.com/Countly/countly-sdk-ios/commit/6770a73eb4cfa79469a367917c5150b65945eb9f

**Comment by armcknight** [comment]
Yay! Thanks @erkanyildiz 🙏
