### ISSUE TITLE
Looking for an equivalent for halt()

### ISSUE THREAD

**Issue by ThomasGoehringer** [Countly/countly-sdk-ios#166]
In my app, user's are able to switch the country. Not every country has a Countly app key, so init would be called with empty values. On Android I work around this by calling `halt()` instead, but the iOS SDK has no such method. What can I do to tell Countly to stop tracking when it can't be initiated with a URL and app key?

### Expected Behavior
Provide a method to disable tracking.

### Current Behavior
No method for disable tracking.

### Your Environment
* Countly iOS SDK version: 20.04.2

**Comment by erkanyildiz** [comment]
Hello Thomas,

> when it can't be initiated with a URL and app key?

At that point I assume Countly is not and will not be started, so this should not be problem.
And if you started it previously, and you want to stop and re-init it, currently this is not possible.
But if you just want to stop it, you can utilize Consents feature as a workaround. 
https://support.count.ly/hc/en-us/articles/360037753511-iOS-watchOS-tvOS-macOS#consents
If you cancel all consents, then Countly iOS SDK will stop working as you wish.
