### ISSUE TITLE
pushTestMode cannot be set to public

### ISSUE THREAD

**Issue by lhunath** [Countly/countly-sdk-ios#168]
### Expected Behavior
A method for setting CountlyConfig's `pushTestMode` to public.

### Current Behavior
`pushTestMode` is non-optional / non-nullable and the API documentation suggests it needs to be set to nil for it to use public APNs.

### Possible Solution
Either make `pushTestMode` nullable or define a `CLYPushTestModePublic` constant.

### Your Environment
* Countly `20.04.3`
* iOS `14`

**Comment by erkanyildiz** [comment]
Hello,

> it needs to be set to nil

Can you share where you saw this in documentation? 

`pushTestMode` is for specifying which test mode the SDK should use. 
If you do set a test mode at all, the SDK will use Production APNs by default.

**Comment by lhunath** [comment]
> API documentation suggests it needs to be set to nil for it to use public APNs.
```
 * @discussion If not set, Countly Server will use Production APNs by default.
```

**Comment by lhunath** [comment]
I understand that the expectation is that I should not touch this property.  This issue exists to point out an inconsistency with the fact that:
1. `pushTestMode not set` == Production APNs
and:
2. `pushTestMode` is non-nullable, so it is not possible to "unset" it.

I know you are all "assuming" that production users will just "not touch" the setting, but it is inconsistent to have an API for deciding between APNs, and the option can either be:
- adhoc
- development
- production
but the API only allows you to set it to
- adhoc
- development
and there is no way to set `production`.

Just make it `nullable`.

**Comment by erkanyildiz** [comment]
https://github.com/erkanyildiz/countly-sdk-ios/commit/500f9f9e628321ec66ddd488fe6e1131adf05d52
