### ISSUE TITLE
Maintain a second podspec

### ISSUE THREAD

**Issue by multinerd** [Countly/countly-sdk-ios#169]
Would you guys be open to maintaining a second podspec?

Currently, `PLCrashReporter` forces us to put `use_modular_headers!` in our podspec file.

In your podspec notes, you recognize that the framework is statically built even if the subspec is not used.

Maybe having another podspec, `Countly-Dynamic.podspec` without the `PLCrashReporter` subspec would allow us to keep dynamic frameworks.

**Comment by erkanyildiz** [comment]
Hello,

First of all, I do not even know if it is easily possible to have multiple podspecs in the same repo, and how to handle it, if so.
But anyway, I am not fond of the idea of polluting SDK repo just to fix a CocoaPods system design issue.

Also, in the case of having multiple podspecs, I think it would be better to make default main one dynamic without PLCrashReporter, and have a second podspec only for PLCrashReporter.

Any help regarding this is appreciated.

**Comment by multinerd** [comment]
> First of all, I do not even know if it is easily possible to have multiple podspecs in the same repo, and how to handle it, if so.
> But anyway, I am not fond of the idea of polluting SDK repo just to fix a CocoaPods system design issue.

I've been using a personal fork (re-created today) that does exactly what I was suggesting. 
https://github.com/multinerd/countly-sdk-ios

All I did was created the file `Countly-dynamic.podspec` without the `PL` podspec. 
In my podfile, I used `pod 'Countly-Dynamic', :git => 'https://github.com/multinerd/countly-sdk-ios'`

I did not push this repo to cocoapods so the `, :git => 'https://github.com/multinerd/countly-sdk-ios'` part can be omitted if you choose to go this route

> Also, in the case of having multiple podspecs, I think it would be better to make default main one dynamic without PLCrashReporter, and have a second podspec only for PLCrashReporter.

I agree as well. In this case, `Countly-dynamic.podspec` can be `Countly-PL.podspec` or something similar.
I've created a branch (https://github.com/multinerd/countly-sdk-ios/tree/master2) that takes that approach.

I'm ready to make a PR, just awaiting your response.

**Comment by multinerd** [comment]
@erkanyildiz Pinging because I don't know if you receive notifications after an issue is closed.

**Comment by erkanyildiz** [comment]
Yes, I can get notifications. :D

Thank you for enlightening us on this topic.

Before we proceed with this, we need to handle communication with some customers who use PL via the current podspec file. I will be updating again when things become clear.

Thank you again.

**Comment by multinerd** [comment]
I think the only breaking change for your customers using PL will be changing the name of the  `pod` in their project's `podfile`.

You can notify customers when they run `pod install` by using cocoapods `deprecated` feature
https://blog.cocoapods.org/CocoaPods-0.32/

![image](https://user-images.githubusercontent.com/6367998/99829647-8d0d1e00-2b2a-11eb-9827-4521ae636e1a.png)

**Comment by multinerd** [comment]
Has any decision been made regarding this? 

I highly doubt I am the only one trying to work around this static library issue.

**Comment by erkanyildiz** [comment]
Hello again,

There are still things to discuss internally, but we will probably move towards this change on the next major release:

A default `Countly.podspec` without PL which allows dynamic, 
and a second `Countly-PL.podspec` with PL as a dependency which forces static.

Thank you very much.

**Comment by multinerd** [comment]
Hi, just wondering if any decision has been made. 

Doesn't look like any changes have been made since Dec 2020 in the SDK, so I wouldn't expect any major releases any time soon. 
Would it be possible to keep this issue open until a decision is made?

**Comment by erkanyildiz** [comment]
Hello again, 

I guess there was no objection, so this change will be a part of next major release.

> Would it be possible to keep this issue open until a decision is made if one has not been made?

Let's do so. :)

**Comment by erkanyildiz** [comment]
Completed: https://github.com/Countly/countly-sdk-ios/commit/5266407f257473b2d3ca845a30923fd026e48071

Thank you.

**Comment by multinerd** [comment]
It doesn't look like the cocoapods spec repo was updated to v`21.11.1`. Cocoapods.com shows latest as v`20.11.1`.
also, you will have to push the new `Countly-PL` podspec. something like `pod repo push ./Countly-PL.podspec`

unsure if its being held back for a specific reason but i wanted to bring it to your attention.

**Comment by multinerd** [comment]
nvm, i just saw #185 for why its not available
