### ISSUE TITLE
Consents and switching device id

### ISSUE THREAD

**Issue by felixmusmann** [Countly/countly-sdk-ios#171]
### Expected Behavior

It should be possible to change the device id even when currently no consent is given.

### Current Behavior

If no consent was given or all of them have been revoked, the device id cannot be changed.

### More Description

I am facing an issue, when I want to change users in the app and the previous user has revoked their consents. In this app the device id is supposed to represent the user id from the application backend. Currently, I would have to re-enable at least one consent to be able to set a new device id, but this will also set the corresponding consent for the previously set device id in the Countly backend. This should not be the case in my opinion. Is there a way to work around this? What is the reasoning behind this condition?

### Your Environment

* Countly iOS SDK version: 20.04.3

**Comment by ar2rsawseen** [comment]
Hello
per GDPR, if consent is not given, we cannot even store device_id on the device (thus we cannot also update it), not even speaking about sending anything to the server. This simply goes against GDPR logic. That would be the reasoning behind this condition :)

**Comment by felixmusmann** [comment]
I understand. Thank you for your fast response! So how would you suggest to handle this situation?

**Comment by ar2rsawseen** [comment]
Well, that depends on the end goal here. Do you want to simply change the device id or merge the old one to the new one when changing?
In your app, if you can implement the logic to check the device id and always attempt to change it if it is not correct, then eventually, if the user ever gives consent, this will be done and sent to the server

But if you want to merge that data and have already correct data on the server right away, you can use Countly API to change device id to a new one by merging yourself, without SDK, and process all users in that way.

**Comment by felixmusmann** [comment]
The data should not be merged. The problem I see with changing the device id after giving the consent, that this consent would be given for the a device id, that was previously set for another user and not the new one. I set the id just after the user has logged in, in case the consent is given.

**Comment by ar2rsawseen** [comment]
This seems like actually the case for which merging is for.
But let's back up a bit.
Can you describe your whole process and usage of SDK?

**Comment by felixmusmann** [comment]
If I understood the merging correctly, it would trigger a process on the server where every data point for the "old id" would be changed to the "new id".

So, to back up a little bit: The SDK is initialized with the temporary device id and consents required. After the user is authenticated the consents are set and the user id is set as device id. This is the same, if the app is closed and reopened. So far so good. Now, if the user cancels the consent, this is also sent to the Countly backend - perfect. But if the user now logs out and another user, who gave the consent, logs in I can't change the device id before setting the consent. The device id is still set to the old users id. If I set the consents, the SDK will send this for the old user to the backend. This is not true. In my opinion I would need some way to reinitialize the SDK (or set the device id without consents. Am I missing something?

**Comment by felixmusmann** [comment]
I tinkered a little bit more and realized, that not using the sharedInstance would give me the option to manage my own Countly instance and initialize a new one, when the user logs out. I guess this solves it for me. 🙂 Or would you see any problem with that? In any case, thank you for your support!

**Comment by felixmusmann** [comment]
Seeing that the Android SDK has a private constructor for the Countly instance, I wonder if ignoring the sharedInstance is such a good solution to this problem. @ar2rsawseen, do you have any thoughts on this?

**Comment by ar2rsawseen** [comment]
Wow, that is a very complicated case :D
@ArtursKadikis this sounds more up to your alley :)

**Comment by erkanyildiz** [comment]
I guess it is better to go on Android related discussion on https://support.count.ly or https://github.com/Countly/countly-sdk-android/issues.

**Comment by felixmusmann** [comment]
Well, it is not really Android related. I rather wonder about the different behaviour compared to the Android SDK, which also allows to [set the temporary device id even if no consent is given](https://github.com/Countly/countly-sdk-android/blob/dda74c0e8b2b9f34a525cc64e2a83b74d514dc73/sdk/src/main/java/ly/count/android/sdk/Countly.java#L2592-L2602). This would already solve my case.

**Comment by ArtursKadikis** [comment]
Sometimes there are some minor implementation differences betwean SDK's.
