### ISSUE TITLE
Support numbers and boolean value types for custom user profile data

### ISSUE THREAD

**Issue by felixmusmann** [Countly/countly-sdk-ios#174]
### Expected Behavior

It is possible to _set_ numbers or booleans as values for custom user details

### Current Behavior

Only strings can be set as value. Numbers are currently only possible by increment, multiply, etc. This does not match the description in the Documentation:

> **Custom user data:** Any data sent alongside the standard data. This data can be in the form of a key-value pair and may contain any type of data (e.g. boolean, string, number, etc.). As data is stored in the sub object named ‘custom’, there are no limitations in naming (as they won’t clash with existing values), apart from the standard MongoDB key limitations not containing a “.” nor starting with a “$”. Therefore, any dot and $ symbols will be stripped from custom keys.

### Possible Solution

Add methods for setting custom user profile data with numbers and boolean types.

### Your Environment

* Countly iOS SDK version: 20.11

**Comment by erkanyildiz** [comment]
I think you are suggesting something like these:

```
- (void)set:(NSString *)key numberValue:(NSNumber *)numberValue;
- (void)set:(NSString *)key boolValue:(BOOL)boolValue;
```

in addition to existing 
```
- (void)set:(NSString *)key value:(NSString *)value;
```

method, and the other ones which only accept `NSString` as value?

I think we can add this on the next major release.

Thank you very much.

**Comment by felixmusmann** [comment]
Exactly, this would be great! Thank you.

**Comment by erkanyildiz** [comment]
Here it is: https://github.com/Countly/countly-sdk-ios/commit/8d774fb65c39521dd162253543ab7a85176c97e1
