### ISSUE TITLE
No crashes being reported

### ISSUE THREAD

**Issue by bb-git** [Countly/countly-sdk-ios#178]
I see no crashes being reported on the server.

### Expected Behavior
Crashes should be sent to the server and show up in the request logs.

### Current Behavior
If I trigger a crash, it just doesn't show up. Still the crash free users / session change, what is very strange...

### Screenshots (if appropriate):
<img width="1431" alt="Bildschirmfoto 2021-06-22 um 16 32 26" src="https://user-images.githubusercontent.com/7348507/122966765-62ba6200-d392-11eb-8d0d-81e72e5e9baf.png">

### Steps to Reproduce (for bugs)
1. I added a `fatalError()`and restarted the app afterwards, no crash popping up

### Comments
Rest is working as expected, only no Crashes are coming in.

### Your Environment
* Countly iOS SDK version 20.11.1 (somehow Cocoapods doesn't want to update to 20.11.2)
* Your iOS version 14.5
* Any changes you have made to this SDK ---

**Comment by erkanyildiz** [comment]
Please use https://support.count.ly for support requests regarding the issues you are experiencing.
Thank you.
