### ISSUE TITLE
Fails to build on Xcode 13 beta 3 due to unguarded use of UIApplication.

### ISSUE THREAD

**Issue by lhunath** [Countly/countly-sdk-ios#179]
Since Xcode 13 beta 3 it is now a build error to use `UIApplication` (or other API unavailable to app extensions) in a library without annotating the library code as unavailable to app extensions.

> Linking Swift packages from application extension targets or watchOS applications no longer emits unresolvable warnings about linking to libraries not safe for use in application extensions. This means that code referencing APIs annotated as unavailable for use in app extensions must now themselves be annotated as unavailable for use in application extensions, in order to allow that code to be used in both apps and app extensions. (66928265)

The upshot of this is that once the Countly code is annotated properly, it should be possible to selectively use Countly safely from within app extensions (though perhaps shared storage might be important?).

For now, the Countly iOS SDK is essentially dead in the water on Xcode 13, even for applications that do not use app extensions, so I would consider this a critical level issue.

Note, this situation is related to #150 but the changes introduced in Xcode 13 are making it more pressing.

# More Information

https://twitter.com/twannl/status/1415643870512226307
https://forums.swift.org/t/set-application-extension-api-only-on-a-spm-package/39333/20

**Comment by erkanyildiz** [comment]
From Xcode 13 Beta 5 Release Notes:

Resolved in Xcode 13 Beta 5
You don’t need to annotate code as unavailable for use in application extensions if it references APIs annotated as unavailable for use in application extensions. This reverts a requirement that Xcode 13 Beta 3 introduced. (80615922) (FB9332020)
