### ISSUE TITLE
CountlyFeedbackWidget getData not available

### ISSUE THREAD

**Issue by ThomasGoehringer** [Countly/countly-sdk-ios#185]
### Expected Behavior
According to your documentation (https://support.count.ly/hc/en-us/articles/360037753511-iOS-watchOS-tvOS-macOS#manually-recording-feedback-widgets) I should be able to retrieve the data of a `CountlyFeedbackWidget` by calling `getData` on it, after retrieving the widget with `Countly.sharedInstance().getFeedbackWidgets`.

### Current Behavior
There is no function `getData` in a `CountlyFeedbackWidget` object.

### Your Environment
* Countly iOS SDK version: 20.11.1

**Comment by ThomasGoehringer** [comment]
This version cannot be found with CocoaPods

**Comment by ArtursKadikis** [comment]
You can find the latest release here:
https://github.com/Countly/countly-sdk-ios/releases

It is not available on CocoaPods due to this: 
https://github.com/CocoaPods/CocoaPods/issues/10065

**Comment by multinerd** [comment]
I was able to clone the repository and push to a new spec. Did you get any errors when you tried to publish?

https://github.com/CocoaPods/Specs/commit/c8860c88ac264fceb7e5cf16f103620bdf64cbe3

**Comment by bb-git** [comment]
And how to update the pod now?

**Comment by multinerd** [comment]
> And how to update the pod now?

Just add the git path `, :git => 'https://github.com/Countly/countly-sdk-ios'`

**Comment by bb-git** [comment]
This updates it to head, and this is really not what I want.

There are also quite some solutions available: https://github.com/CocoaPods/CocoaPods/issues/10065#issuecomment-694266259

**Comment by multinerd** [comment]
> This updates it to head

if you don't specify any other parameters. You can reference a specific branch, a commit hash, whatever...
