### ISSUE TITLE
Not able to update Countly 20.11.1 to newer version via cocoapods

### ISSUE THREAD

**Issue by bb-git** [Countly/countly-sdk-ios#186]
Not able to update Countly 20.11.1 to newer version via cocoapods

### Expected Behavior
When running `pod update` or `pod outdated`new versions should appear.
also `pod repo update` does not change anything

### Current Behavior
New cocoapod version does not show up. Also specifying the version does not help
`[!] CocoaPods could not find compatible versions for pod "Countly":
  In Podfile:
    Countly (= 20.11.3)

None of your spec sources contain a spec satisfying the dependency: `Countly (= 20.11.3)`.
`

### Your Environment
* Countly iOS SDK version: 20.11.1
* Your iOS version: 15.0.2
* Any changes you have made to this SDK: -

**Comment by erkanyildiz** [comment]
https://github.com/Countly/countly-sdk-ios/issues/185#issuecomment-944116843

**Comment by multinerd** [comment]
see my comment https://github.com/Countly/countly-sdk-ios/issues/185#issuecomment-974306286
