### ISSUE TITLE
Background task that isn't ended

### ISSUE THREAD

**Issue by mahboud** [Countly/countly-sdk-ios#190]
Has this been reported?

`[BackgroundTask] Background Task 1 ("Called by FirstContact, from -[CountlyConnectionManager proceedOnQueue]"), was created over 30 seconds ago. In applications running in the background, this creates a risk of termination. Remember to call UIApplication.endBackgroundTask(_:) for your task in a timely manner to avoid this.`

**Comment by erkanyildiz** [comment]
Hello!

When there are request to be sent in the queue, the SDK starts a background task to continue sending the requests even while in the background. You may experience this warning if there are too many requests in the queue and/or connection is too slow. As soon as all the requests are completed successfully, background task is ended. In worst case, background task is ended in expiration handler of `beginBackgroundTaskWithExpirationHandler` just before allowed background time reaches 0 to avoid app termination.
