### ISSUE TITLE
Regression causes crash when logging out current user

### ISSUE THREAD

**Issue by lhunath** [Countly/countly-sdk-ios#191]
The issue is related to the following commit by @erkanyildiz:

```
commit 46a8052d7e7a11525e45a3add8b28b7aa73c4fe1
Author: erkanyildiz <ey@count.ly>
Date:   Thu Jun 24 10:45:01 2021

    Applied max key length for user details properties
```

Here, we see changes which blindly throw away the typing on the user details' properties and assume them all to be strings:
```
-userDictionary[kCountlyUDKeyName] = self.name;
+userDictionary[kCountlyUDKeyName] = [(NSString *)self.name cly_truncatedValue:@"User details name"];
```

Of course, types exist for a reason, and in this case, the type `id<CountlyUserDetailsNullableString>` describes an object that can either be an `NSString` or an `NSNull`, since `NSNull` is intended to be used for clearing the current value in the property.

This force cast results in the following runtime crash:
```
-[NSNull cly_truncatedValue:]: unrecognized selector sent to instance 0x1db7c8558
```

I suggest that you perform a safe check against the type before doing casts, or expose `cly_truncatedValue` on `CountlyUserDetailsNullableString` so you can use it safely.

**Comment by erkanyildiz** [comment]
Thank you very much for reporting. 

While I added the type check for `.custom` property of type `id<CountlyUserDetailsNullableDictionary>`, it appears that I forgot to do the check for string properties.

And your fix seems fine. So, thank you again for the fix also.

I will merge it and make a minor release 21.11.1 soon.

**Comment by erkanyildiz** [comment]
Done! https://github.com/Countly/countly-sdk-ios/releases/tag/21.11.1
