### ISSUE TITLE
Installation method: XCFramework

### ISSUE THREAD

**Issue by AshStefanOltmann** [Countly/countly-sdk-ios#196]
Please provide the installation method as XCFramework.

This is the simplest way to add a library to a Swift project without the hassle that comes with dependency managers like CocoaPods.

Sentry has an XCFramework package on it's GitHub release page: https://github.com/getsentry/sentry-cocoa/releases/tag/7.10.2

Can you please do the same?

**Comment by AshStefanOltmann** [comment]
@ArtursKadikis Is macOS actually supported any more now or are the docs outdated?

**Comment by ArtursKadikis** [comment]
Hello, we test and validate carthage integration only with iOS. On that platform it should work with the regular '.framework' format. Currently 'xcframework' integration with carthage is not something that we are validating.
