### ISSUE TITLE
'-[OS_xpc_dictionary path]: unrecognized selector sent to instance

### ISSUE THREAD

**Issue by spalomino-atiba** [Countly/countly-sdk-ios#205]
I'm getting some weird crash when trying to initialize Countly for the first time. Something with trying to read the path isn't working. This is happening when using the minimal setup code snippet with my custom server. I can see some events come through on my server but my app crashes on startup here and seems to come from trying to run 
`BOOL writeResult = [saveData writeToFile:[self storageFileURL].path atomically:YES];`

```
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[OS_xpc_dictionary path]: unrecognized selector sent to instance 0x2813f4780'
terminating with uncaught exception of type NSException
```

**Comment by ArtursKadikis** [comment]
As far as we could investigate, we could not reproduce this issue.
Our current guess is that the problem would be caused by the specific environment it was run in.
