### ISSUE TITLE
Version 22.06.2 not available on Cocoapods

### ISSUE THREAD

**Issue by Zandor300** [Countly/countly-sdk-ios#208]
The latest version of the iOS Countly SDK isn't available on Cocoapods. The latest version on Cocoapods is 21.11.2. (See [cocoapods.org](https://cocoapods.org/pods/Countly))

Could the latest version(s) be pushed to Cocoapods please?

**Comment by jkorany** [comment]
Any update on this?

**Comment by jkorany** [comment]
Any update on this?

**Comment by Zandor300** [comment]
Version 22.06.2 was released on Cocoapods 3 days ago.

https://github.com/CocoaPods/Specs/commit/a8bce6b8f172a48a8952fc89b0a97dddd1fc0f01
