### ISSUE TITLE
macOS build errors

### ISSUE THREAD

**Issue by DarrellBrogdon** [Countly/countly-sdk-ios#232]
### Expected Behavior

After implementing the [iOS, watchOS, tvOS & macOS instructions ](https://support.count.ly/hc/en-us/articles/360037753511-iOS-watchOS-tvOS-macOS#swift-package-manager-spm) and building, I would expect the build to complete without without any errors.

### Current Behavior

I'm getting the following errors after building:

- Property 'sharedInstance' not found on object of type 'CountlyServerConfig' (CountlyPersistency.m line 74)
- Property implementation must have its declaration in interface 'CountlyServerConfig' or one of its extensions (CountlyServerConfig.m lines 16 & 17)
- 

### Screenshots (if appropriate)
<img width="340" alt="Screenshot 2023-05-31 at 5 24 41 PM" src="https://github.com/Countly/countly-sdk-ios/assets/196196/ea8720fc-be6e-4359-a32b-8f511b9f2b22">

### Steps to Reproduce (for bugs)

1. Implement the [iOS, watchOS, tvOS & macOS instructions ](https://support.count.ly/hc/en-us/articles/360037753511-iOS-watchOS-tvOS-macOS#swift-package-manager-spm)
2. Add some `recordEvent()` statements in the code
3. Click Product > Build (⌘B)
4. See errors 

### More Description

Trying to run the app

### Your Environment

* Countly iOS SDK version: Latest installed through Swift Package Manager
* Your iOS version: macOS 13.4 (22F66)
* Any changes you have made to this SDK: None

**Comment by ijunaid** [comment]
Hello @DarrellBrogdon,
We encountered an issue with a tag targeting the wrong code, but we have resolved it by fixing the tag. It is now correctly pointing to the correct code. Could you update your packages and retest to verify the resolution?

**Comment by DarrellBrogdon** [comment]
Updated to 23.2.2 but I'm still getting an error in CountlyRemoteConfig.swift line 128:  "Property 'sharedInstance' not found on object of type 'CountlyServerConfig'"

<img width="1390" alt="Screenshot 2023-06-01 at 4 07 03 AM" src="https://github.com/Countly/countly-sdk-ios/assets/196196/b4a858bb-803b-4d11-a8d9-18700641e98a">

**Comment by ijunaid** [comment]
Hello @DarrellBrogdon,
Swift package wasn’t updated when we resolved the targeting issue in the GitHub release. However, we have now released an updated version (23.2.3) that includes the necessary fixes for the issue. If you are still experiencing any problems, please do not hesitate to let us know.
