### ISSUE TITLE
Build error: 'CountlyRCData.h' file not found in version 23.6.0

### ISSUE THREAD

**Issue by theanhaxon** [Countly/countly-sdk-ios#236]
I created the new iOS project with Swift language then using SPM to add Countly **version 23.6.0**
The issue I got is cannot build the project. When I build project, Xcode reported an error: **'CountlyRCData.h' file not found**
You can refer to the following image for detail error.
**This issue doesn't happen in version 23.2.3**

### Expected Behavior
After integrating Countly version 23.6.0 into iOS project, we can build the project successfully.

### Current Behavior
I cannot build iOS project after integrating Countly version 23.6.0 via SPM

### Screenshots (if appropriate)
![Screenshot 2023-07-05 at 15 53 04](https://github.com/Countly/countly-sdk-ios/assets/100405076/31809d01-335a-456d-a8d8-94328ee0a126)

### Steps to Reproduce (for bugs)

1. Create a new iOS project
2. import Countly version 23.6.0 via SPM
3. Build the iOS project (Command+B)
4. Updating step: You need to import Countly on your project.
Example: 
`import Countly` at your AppDelegate.swift
6. See the error log

### Your Environment

* Countly iOS SDK version 23.6.0
* My iOS version 16.1
* My Xcode version 14.1 (14B47b)

**Comment by ijunaid** [comment]
Hey @theanhaxon,
I followed the steps you mentioned to replicate the problem, but unfortunately, I couldn’t reproduce it.
Could you please provide a sample project that exhibits this issue?

**Comment by theanhaxon** [comment]
[CountlyExample.zip](https://github.com/Countly/countly-sdk-ios/files/11956779/CountlyExample.zip)
Below is the example project that I make.

**Comment by theanhaxon** [comment]
Updating step: You need to import Countly into your project.
Example: `import Countly` at AppDelegate.swift file

**Comment by ijunaid** [comment]
Upon adding `import Countly` to the AppDelegate.swift file, I successfully reproduced the issue you mentioned.
Thank you for sharing the example app and providing additional steps to replicate the problem. Our team is currently working on resolving it, and we will include the fix in the upcoming release.

**Comment by ijunaid** [comment]
Hi @theanhaxon 
This has been resolved in the latest release, version 23.6.1. If you are still experiencing any difficulties, please don't hesitate to notify us. We are here to assist you further.
