### ISSUE TITLE
After Updating to Release 23.8.0: `'CountlyViewTracking.h' file not found`

### ISSUE THREAD

**Issue by daloli14** [Countly/countly-sdk-ios#247]
### Expected Behavior
Building the project without issues

### Current Behavior
Xcode complaints `'CountlyViewTracking.h' file not found`

### Screenshots (if appropriate)
<img width="468" alt="image" src="https://github.com/Countly/countly-sdk-ios/assets/144109775/5f16cd3e-a0ec-4801-86de-aea6e2a90573">

<img width="1010" alt="image" src="https://github.com/Countly/countly-sdk-ios/assets/144109775/6cf7e030-e057-4502-86a3-ed736efb6cae">

### Steps to Reproduce (for bugs)
Just building the project with Countly 23.8.0

### Your Environment

* Countly iOS SDK version: 23.8.0
* Your iOS version: 16.4

**Comment by ijunaid** [comment]
Hi @daloli14,
Thank you for informing us. Based on our observations, the issue only occurred when using SPM for building. Building the project by directly adding the source code did not result in any problems. We intend to release a version today that includes the fix.
