### ISSUE TITLE
Crash in Countly_OpenUDID

### ISSUE THREAD

**Issue by pushkarsingh** [Countly/countly-sdk-ios#27]
We are using Segment.iO

Stack trace
----------------
Fatal Exception: NSInvalidArgumentException NSInvalidArgumentException
+[UIPasteboard _accessibilityUseQuickSpeakPasteBoard]: unrecognized selector sent to class 0x3a201828

Countly_OpenUDID.m line 92
+[Countly_OpenUDID _getDictFromPasteboard:]

Countly_OpenUDID.m line 231
+[Countly_OpenUDID valueWithError:]
Countly.m line 477
-[ConnectionQueue beginSession]
CountlyProvider.m line 30
-[CountlyProvider start]
AnalyticsProvider.m line 36
-[AnalyticsProvider updateSettings:]
Analytics.m line 213
-[Analytics updateProvidersWithSettings:]
Analytics.m line 208
-[Analytics setCachedSettings:]
Analytics.m line 232
__28-[Analytics refreshSettings]_block_invoke_2

**Comment by willonboy** [comment]
Add a category of UIPasteboard. 
Like this:
@interface UIPasteboard (Ext)

+ (void)_accessibilityUseQuickSpeakPasteBoard;

+ (void)accessibilityUseQuickSpeakPasteBoard;

@end

**Comment by erkanyildiz** [comment]
You can use IDFA as an alternative to OpenUDID to avoid UIPasterBoard related OpenUDID problems such as this one.
