### ISSUE TITLE
Can't use PLCrashReporter

### ISSUE THREAD

**Issue by cherpake** [Countly/countly-sdk-ios#319]
I'm trying to switch to PLCrashReporter but I'm always getting "PLCrashReporter dependency can not be found in Project" exception. 

My Podfile looks like this:

```
target 'Control' do
  use_frameworks!
  pod 'Countly-PL/PL', :git => 'https://github.com/Countly/countly-sdk-ios.git', :branch => "master".
  pod 'PLCrashReporter'
end
```

I'm sure I'm doing something wrong, but can't figure out what.

**Comment by cherpake** [comment]
This is solved by manually adding -framework "CrashReporter" to Other linker flags for Countly target in Pods project

**Comment by cherpake** [comment]
Seems like this hack is working:

`
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if target.name  == "Countly"
          config.build_settings['OTHER_LDFLAGS'] ||= ['$(inherited)']
          config.build_settings['OTHER_LDFLAGS'] << '-framework "CrashReporter"'
      end
    end
  end
end`

**Comment by cherpake** [comment]
or not :( I'm not sure what's going on anymore...

**Comment by cherpake** [comment]
OK, seems I need this too

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if target.name  == "Countly"
          config.build_settings['OTHER_LDFLAGS'] ||= ['$(inherited)']
          config.build_settings['OTHER_LDFLAGS'] << '-framework "CrashReporter"'
          
          config.build_settings['LIBRARY_SEARCH_PATHS'] ||= ['$(inherited)']
          config.build_settings['LIBRARY_SEARCH_PATHS'] << "${PODS_XCFRAMEWORKS_BUILD_DIR}/PLCrashReporter"
          config.build_settings['FRAMEWORK_SEARCH_PATHS'] ||= ['$(inherited)']
          config.build_settings['FRAMEWORK_SEARCH_PATHS'] << "${PODS_XCFRAMEWORKS_BUILD_DIR}/PLCrashReporter"
      end
    end
  end
end
```

**Comment by ijunaid** [comment]
Hi @cherpake,
Thank you for reporting the issue and providing the solution. We are able to reproduce the issue and with your solution it works fine. We've also updated the SDK documentation accordingly.
Apologies for the delayed response.
