### ISSUE TITLE
Crash on CountlyViewTrackingInternal.m line 549

### ISSUE THREAD

**Issue by thien-axonvibe** [Countly/countly-sdk-ios#361]
I just got the crash when let the app in foreground for a while without any interactions. It's caused on the function startStoppedViewsInternal line 549 of CountlyViewTrackingInternal.m (attached image below). It happened rarely on iOS18 device. Please investigate this weird crash. Thank you so much.

### Screenshots (if appropriate)
![Screenshot 2024-11-15 at 09 31 12](https://github.com/user-attachments/assets/541d015c-4708-40c2-a12a-315768dd75b0)

### Your Environment

* Countly iOS SDK version - 24.7.7
* Your iOS version - iOS18
* Any changes you have made to this SDK - migrate from 24.7.3 to 24.7.7

**Comment by thien-axonvibe** [comment]
FYI: It crashed when opening from background
![Screenshot 2024-11-20 at 17 37 13](https://github.com/user-attachments/assets/09807d6c-d24a-4087-b2c5-69573be9d769)

**Comment by turtledreams** [comment]
Hu @thien-axonvibe, this should be fixed now with version 24.7.8
