### ISSUE TITLE
Crash on changeDeviceIDWithoutMerge

### ISSUE THREAD

**Issue by cci-bucolak** [Countly/countly-sdk-ios#369]
We identify crash on _changeDeviceIDWithoutMerge_  function. Even if string has a value but its crashing exactly on 

> [self.viewDataDictionary enumerateKeysAndObjectsUsingBlock:^(NSString * _Nonnull key, CountlyViewData * _Nonnull viewData, BOOL * _Nonnull stop) {

### Expected Behavior

Function should execute properly without any crash.

### Current Behavior

Its crashing and reducing our crash-free ratio.

### Screenshots (if appropriate)
-

### Possible Solution

It could be possible that like there is retain object and there is a memory leak thus crash occurs.

### Steps to Reproduce (for bugs)

1. Login app
2. Call _changeDeviceIDWithoutMerge_
3. Crash

### Your Environment

* Countly iOS SDK version : 24.7.7
* Your iOS version: 18.0
* Any changes you have made to this SDK: Nothing.

**Comment by arifBurakDemiray** [comment]
Hello @cci-bucolak; 🙌 

We sincerely apologize for the delayed response. 🙇  Thank you for your patience!

We're happy to inform you that the issue you reported has been resolved in release 
https://github.com/Countly/countly-sdk-ios/releases/tag/24.7.8

If you have any more questions or run into any issues, feel free to reach out.

**Comment by cci-bucolak** [comment]
Hi @arifBurakDemiray 
No worries, thank you for fixing the issue.

We will upgrade our version to 24.7.8 and try out the new version.

Thanks a lot for your efforts.

Regards,
Burak
