### ISSUE TITLE
Crash when dismissing push notification alerts

### ISSUE THREAD

**Issue by Dids** [Countly/countly-sdk-ios#41]
Sending push notifications from Countly (Community Edition), for example one that should open a URL, simply crashes when I tap "Open" on the UIAlertView that comes up.

The crash occurs on line 984 of Countly.m:
[self recordPushActionForCountlyDictionary:info[@"c"]];

**Comment by derekmoorecountly** [comment]
It's a known bug and will be fixed in next release.

**Comment by erkanyildiz** [comment]
It is solved now.
