### ISSUE TITLE
Enable Debug from external class

### ISSUE THREAD

**Issue by dieskim** [Countly/countly-sdk-ios#44]
Hi,

It would be great to be able to enable debugging in Countly.m from an external class. Something like:

-(void)setDebug:(BOOL)debugVar

**Comment by erkanyildiz** [comment]
Hi, 

Thanks for the suggestion but we believe keeping debug flag as a preprocessor directive is better in means of both code simplicity and performance.

**Comment by dieskim** [comment]
Once again I will open this issue - I understand you believe its better for code simplicity and performance - but with the value being a preprocessor value there is NO way for a 3rd party module / implementation of the Countly SDK to be able to set this value. 

Thus there is no way to enable/disable Countly Debugging from within a 3rd party module / implementation like my Appcelerator Titanium Modules.

The user using the modules would need to change the preprocessor value and Recompile the module - something most users would not do or even know how to do?
