### ISSUE TITLE
Eclipse/Titanium Development Build never sets testMode to 1

### ISSUE THREAD

**Issue by dieskim** [Countly/countly-sdk-ios#45]
When Building our app under Eclipse/Titanium, Development Build never sets testMode to 1

I guess __OPTIMIZE__ is being set even in Development Build.

```
 // Test modes: 0 = production mode, 1 = development build, 2 = Ad Hoc build
    int testMode;
#ifndef __OPTIMIZE__
    testMode = 1;
#else
    testMode = self.startedWithTest ? 2 : 0;
#endif
```

I like the the idea of trying to detect for production, Ad Hoc or Development but I have only ever seen Production and Development detection. If we only checked for those two it would be simple.

I really dont want to have to edit the Countly.m SDK files to make this work in Titanium.

I will update if I find a solution

**Comment by dieskim** [comment]
Here is my suggested fix - https://github.com/Countly/countly-sdk-ios/pull/46

**Comment by erkanyildiz** [comment]
@iartem if you don't have any more comments, I'll keep this issue closed.
