### ISSUE TITLE
Release 15.0.6 on CocoaPods

### ISSUE THREAD

**Issue by f2prateek** [Countly/countly-sdk-ios#49]
The 3.0.0 tag was deleted so CocoaPods can't install that, while 15.0.6 is not published on CocoaPods yet.

**Comment by adrienkohlbecker** [comment]
+1, can't install

**Comment by erkanyildiz** [comment]
I believe it is OK now.

**Comment by vtaneeru** [comment]
CocoaPods install not working for Countly

**Comment by gorkem-cetin** [comment]
@vtaneeru we'll fix it very soon as many depend on it. You can see latest status of this bug and comment it on https://github.com/Countly/countly-sdk-ios/issues/62
