### ISSUE TITLE
Watchkit compile errors

### ISSUE THREAD

**Issue by ddaddy** [Countly/countly-sdk-ios#50]
I've just updated a current project with the latest version of the iOS SDK and added it to a WatchKit target.
I am getting a couple of errors in ```CountlyDB.m```. First of all, line 85, ```Use of undeclared identifier 'WKInterfaceDevice'```
I don't see you importing WatchKit anywhere in ```CountlyDB.m```

As a workaround, i've added ```#import <WatchKit/WatchKit.h>``` to line 22 underneath ```#if COUNTLY_TARGET_WATCHKIT```

The final 2 errors are on line 86 ```postData = [postData stringByAppendingFormat:@"&segment=%@", CountlyURLEscapedString(segmentation)];```
Error: ```Implicit declaration of function 'CountlyURLEscapedString' is invalid in C99```
Warning: ```Format specifies type 'id' but the argument has type 'int'```

I'm not sure how to fix this.

Thanks

**Comment by ddaddy** [comment]
```NSString* CountlyURLEscapedString(NSString* string);``` seems to be an internal method to ```Countly.m``` and not exposed to ```CountlyDB.m```

**Comment by erkanyildiz** [comment]
Thank you very much for reporting this issue. 
I just figured out that I had tested the SDK on another configuration, so I did not notice it before pushing.

This commit should fix it:
https://github.com/Countly/countly-sdk-ios/commit/93b7dd9f16489e151d70fba48bb5092757cd20ae
