### ISSUE TITLE
Countly issue through the segment integration

### ISSUE THREAD

**Issue by gorkem-cetin** [Countly/countly-sdk-ios#51]
This is a Countly issue, but through the segment integration. We recently had to downgrade our countly integration from 3.0.0 to 1.11.13 because of unhandled exceptions when [SEGAnalytics flushMessageQueue] was being called.  Here’s part of our crash log:

<pre>
Application Specific Information:
*** Terminating app due to uncaught exception 'NSGenericException', reason: '*** Collection <__NSCFSet: 0x17067da00> was mutated while being enumerated.'

Last Exception Backtrace:
0   CoreFoundation                       0x00000001858102d8 __exceptionPreprocess + 132
1   libobjc.A.dylib                      0x000000019703c0e4 objc_exception_throw + 56
2   CoreFoundation                       0x000000018580fc8c __NSFastEnumerationMutationHandler + 136
3   CoreData                             0x00000001854f0018 -[NSSQLCore prepareForSave:] + 920
4   CoreData                             0x00000001854ef3e4 -[NSSQLCore saveChanges:] + 652
5   CoreData                             0x00000001854b70a0 -[NSSQLCore executeRequest:withContext:error:] + 716
6   CoreData                             0x0000000185583c08 __65-[NSPersistentStoreCoordinator executeRequest:withContext:error:]_block_invoke + 4128
7   CoreData                             0x000000018558c028 gutsOfBlockToNSPersistentStoreCoordinatorPerform + 180
8   libdispatch.dylib                    0x000000019768d954 _dispatch_client_callout + 12
9   libdispatch.dylib                    0x00000001976971e4 _dispatch_barrier_sync_f_invoke + 72
10  CoreData                             0x000000018557de98 _perform + 176
11  CoreData                             0x00000001854b6c5c -[NSPersistentStoreCoordinator executeRequest:withContext:error:] + 296
12  CoreData                             0x00000001854ddbf4 -[NSManagedObjectContext save:] + 1280
13  AA-DEV                     0x0000000100149144 -[CountlyDB saveContext] (CountlyDB.m:168)
14  AA-DEV                     0x0000000100148a4c -[CountlyDB createEvent:count:sum:segmentation:timestamp:] (CountlyDB.m:67)
15  AA-DEV                     0x0000000100141b70 -[CountlyEventQueue recordEvent:segmentation:count:] (Countly.m:546)
16  AA-DEV                     0x0000000100144d1c -[Countly recordEvent:segmentation:count:] (Countly.m:1053)
17  AA-DEV                     0x0000000100123a9c -[SEGCountlyIntegration track:properties:options:] (SEGCountlyIntegration.m:74)
18  AA-DEV                     0x0000000100123b50 -[SEGCountlyIntegration screen:properties:options:] (SEGCountlyIntegration.m:81)
19  CoreFoundation                       0x0000000185816100 __invoking___ + 140
20  CoreFoundation                       0x00000001857122fc -[NSInvocation invoke] + 292
21  CoreFoundation                       0x0000000185716e30 -[NSInvocation invokeWithTarget:] + 64
22  AA-DEV                     0x000000010011f8c8 -[SEGAnalytics invokeIntegration:selector:arguments:options:] (SEGAnalytics.m:401)
23  AA-DEV                     0x000000010011f5e4 -[SEGAnalytics forwardSelector:arguments:options:] (SEGAnalytics.m:366)
24  AA-DEV                     0x000000010011fee0 -[SEGAnalytics flushMessageQueue] (SEGAnalytics.m:426)
25  AA-DEV                     0x0000000100122744 seg_dispatch_specific (SEGAnalyticsUtils.m:60)
26  AA-DEV                     0x00000001001227a0 seg_dispatch_specific_async (SEGAnalyticsUtils.m:71)
27  AA-DEV                     0x000000010011ebe0 -[SEGAnalytics updateIntegrationsWithSettings:] (SEGAnalytics.m:279)
28  AA-DEV                     0x000000010011e9a0 -[SEGAnalytics setCachedSettings:] (SEGAnalytics.m:271)
29  AA-DEV                     0x000000010011ef98 __31-[SEGAnalytics refreshSettings]_block_invoke_2 (SEGAnalytics.m:301)
30  libdispatch.dylib                    0x000000019768d994 _dispatch_call_block_and_release + 20
31  libdispatch.dylib                    0x000000019768d954 _dispatch_client_callout + 12
32  libdispatch.dylib                    0x00000001976980a4 _dispatch_queue_drain + 1444
33  libdispatch.dylib                    0x0000000197690a5c _dispatch_queue_invoke + 128
34  libdispatch.dylib                    0x000000019769a318 _dispatch_root_queue_drain + 716
35  libdispatch.dylib                    0x000000019769bc4c _dispatch_worker_thread3 + 104
36  libsystem_pthread.dylib              0x000000019786d22c _pthread_wqthread + 812
37  libsystem_pthread.dylib              0x000000019786cef0 start_wqthread + 0
</pre>

Since downgrading, we’ve had no crashes.

**Comment by erkanyildiz** [comment]
Working on this issue on my own fork:
https://github.com/erkanyildiz/countly-sdk-ios/tree/persistency

It'll be merged when we are done.

**Comment by gorkem-cetin** [comment]
Shall we close this issue if / when it is done?
