### ISSUE TITLE
Terminated due to signal 9

### ISSUE THREAD

**Issue by VictorSharov** [Countly/countly-sdk-ios#52]
Countly crash application with this message: "Terminated due to signal 9" where i press home button (hide application).

**Comment by VictorSharov** [comment]
I think problem in method
- (void)saveContext
{
    NSError *error = nil;
    NSManagedObjectContext *managedObjectContext = [self managedObjectContext];
    if (managedObjectContext != nil)
    {
        if ([managedObjectContext hasChanges] && ![managedObjectContext save:&error])
        {
           COUNTLY_LOG(@"CoreData error %@, %@", error, [error userInfo]);
        }
    }
}
When i write return at start method crash stopped.

**Comment by erkanyildiz** [comment]
You are using App Groups in your project?

It just does not allow write to App Groups when the app goes background.
I'm still waiting for a reply from Apple on this issue.

**Comment by VictorSharov** [comment]
Yes, I use App Group. At the moment the only way to avoid crash Countly - disable AppGroups in Countly and lose tracking AppleWatch?

**Comment by erkanyildiz** [comment]
Actually I'm just trying to discard CoreData in Countly iOS SDK. 
You can see it here on my fork: 
https://github.com/erkanyildiz/countly-sdk-ios/commits/persistency

You can use it to track Apple Watch too.
But currently it cannot store sessions and events for Apple Watch, if there is no internet connection. I'll be working on it this week.
