### ISSUE TITLE
crashTest3 doesn't work.

### ISSUE THREAD

**Issue by xieweizhi** [Countly/countly-sdk-ios#54]
I found that crash caused by `crashTest3` method can't be caught.

running on Xcode7 beta4, iOS 9 simulator.

**Comment by erkanyildiz** [comment]
I've just checked it and it works. You need to test it when the Debugger is not attached. So, please disconnect your app from Xcode and try again. If you think issue still occurs, please let me know.

**Comment by xieweizhi** [comment]
I disconnected the app from Xcode then it worked.  Thanks
