### ISSUE TITLE
Ensure Countly iOS SDK works with iOS 9

### ISSUE THREAD

**Issue by gorkem-cetin** [Countly/countly-sdk-ios#59]
We need to make sure Countly is compatible with iOS 9.

**Comment by erkanyildiz** [comment]
Except new NSAppTransportSecurity rule introduced with iOS9, everything works. For details on NSAppTransportSecurity please see Countly Documentation: http://resources.count.ly/v1.0/docs/countly-sdk-for-ios-and-os-x
