### ISSUE TITLE
iOS9 fixes for iOS SDK

### ISSUE THREAD

**Issue by gorkem-cetin** [Countly/countly-sdk-ios#60]

**Comment by Avisoo** [comment]
I did a small hack to get it working, no guarantees that it's a good way to go about it or anything but here goes.

In the file CountlyDB.m, row 215 you'll find:
```obj-c
NSURL *modelURL = [[NSBundle bundleForClass:[CountlyDB class]] URLForResource:@"Countly" withExtension:@"momd"];
```
Change that to:
```obj-c
NSURL *modelURL = [[NSBundle bundleForClass:[CountlyDB class]] URLForResource:@"Countly" withExtension:@"mom"];
modelURL = [modelURL URLByAppendingPathComponent:@"Countly.mom"];
```

**Comment by ddaddy** [comment]
Was there a need for an iOS 9 fix?

**Comment by Avisoo** [comment]
Well, after updating Xcode to 7 and updating device to iOS9, I got an error like this:

```obj-c
CoreData: Failed to load optimized model at path '/Users/Dev/Library/Developer/CoreSimulator/Devices/D0F33851-8C7C-47CE-80E5-35F91DE4E052/data/Containers/Bundle/Application/EDC11BDA-D0F5-491D-824F-CE76499CF6AA/PushApp.app/Countly.momd/Countly.omo'
```

The app would run like normal except for Countly. The hack I did solved it, but I can't say I know why exactly.

**Comment by ddaddy** [comment]
Ahh ok. Maybe someone else can confirm it. I added the countly model to my existing model.

**Comment by erkanyildiz** [comment]
Objective-C based projects does not experience such a problem. 
Now I'm further investigating the issue with Swift based projects. 
Thanks for your help.

**Comment by erkanyildiz** [comment]
Checked with Swift based project too and did not encounter with any errors. Please make sure you add all Countly iOS SDK files into your project, select correct targets and configure bridging header correctly.

**Comment by Avisoo** [comment]
Using pod 'Countly', '~> 3.0', Objective C

**Comment by Avisoo** [comment]
Now using pod 'Countly', '~> 15.06', same error when not using the hack: "CoreData: Failed to load optimized model at path [...]/Countly.momd/Countly.omo"

**Comment by erkanyildiz** [comment]
Then it might be a CocoaPods integration issue. Can you try it by using repo directly?

**Comment by Avisoo** [comment]
You're right. It's working if I'm not getting Countly as pod. Thanks :)

**Comment by erkanyildiz** [comment]
I see. There might be a need to update podfile or something like that for iOS9. I will look into it.

**Comment by erkanyildiz** [comment]
This issue will be handled here:
https://github.com/Countly/countly-sdk-ios/issues/62
