### ISSUE TITLE
Update podfile for iOS9

### ISSUE THREAD

**Issue by gorkem-cetin** [Countly/countly-sdk-ios#62]
There is a cocoapads integration issue for > iOS9.

**Comment by erkanyildiz** [comment]
It appears it is not about Countly's podfile. 
Just tried it with different test projects and it perfectly works with current podfile on podspecs repo.
https://github.com/CocoaPods/Specs/tree/5e07088fac755758513e8533b934b779361fc3b1/Specs/Countly/15.06.01
