### ISSUE TITLE
Countly Messaging crash - OpenUDID

### ISSUE THREAD

**Issue by dieskim** [Countly/countly-sdk-ios#63]
The crash below only happens the FIRST time you open the app and the user accepts the prompt to Subscribe to Push - after the initial crash it works fine....

Apps crash every now and then when registering for push notifications. Sometimes it works and sometimes it fails and crashed 80% of the time.

After a lot of debugging I think I have narrowed it down to OPENUDID.

When the "data" for the "tokenSession" is created as below it tries to generate the "device_id" via "[CountlyDeviceInfo udid]"

```
NSString *data = [NSString stringWithFormat:@"app_key=%@&device_id=%@&timestamp=%ld&sdk_version="COUNTLY_SDK_VERSION"&token_session=1&ios_token=%@&test_mode=%d",
                      self.appKey,
                      [CountlyDeviceInfo udid],
                      time(NULL),
                      [token length] ? token : @"",
                      testMode];
```

What happens is that OpenUDID does not return a string but crashes with the following error:

```
ly.count.appcelerator[2616] <Warning>: Sending APN token in mode 1
ly.count.appcelerator[2616]: objc[2616]: pthread_rwlock_rdlock failed (11)
```

Sometimes it does not just crash but gets stuck in a loop with "[CountlyDeviceInfo udid]" returning as below:

```
{     "Create Time" = "464935993.428005";
        Expiry = inf;
        "HSTS Host" = 1;
        "Include Subdomains" = 1;
    }
```

I have tried many other things and every time I run "[CountlyDeviceInfo udid]" inside the  (void)tokenSession:(NSString *)token function it causes the app to hang and crash...

Here are some more logs below:

```
ly.count.appcelerator[2381] <Warning>: Request Started
     http://host.com/i?app_key=my_app_key_removed&device_id={
        "Create Time" = "464933394.465819";
        Expiry = inf;
        "HSTS Host" = 1;
    }&timestamp=1443240598&sdk_version=15.06.01&token_session=1&ios_token=my_ios_key_removed&test_mode=1

ly.count.appcelerator[2338] <Warning>: Request Failed
     <NSManagedObject: 0x17d7b850> (entity: Data; id: 0x17d80330 <x-coredata://761E5C6F-919A-4D77-8602-AD69FD341D93/Data/p2> ; data: {
        post = "app_key=my_app_key_removed&device_id={\n    \"Create Time\" = \"464931768.777818\";\n    Expiry = inf;\n    \"HSTS Host\" = 1;\n}&timestamp=1443238972&sdk_version=15.06.01&token_session=1&";
    }): Error Domain=NSURLErrorDomain Code=-1002 "unsupported URL" UserInfo={NSUnderlyingError=0x17d83550 {Error Domain=kCFErrorDomainCFNetwork Code=-1002 "unsupported URL" UserInfo={NSLocalizedDescription=unsupported URL}}, NSLocalizedDescription=unsupported URL}
```

Some times it returns a correct UDID like below but most of the time it fails and then the app crashes.

```
ly.count.appcelerator[2365] <Warning>: Request Started
     http://host.com/i?app_key=my_app_key_removed&device_id=6a016c22435eg78d3fdbffd571c25f0a7a9b9c4e&timestamp=1443239731&sdk_version=15.06.01&begin_session=1&metrics=%7B%22_app_version%22%3A%221.0%22%2C%22_os%22%3A%22iOS%22%2C%22_locale%22%3A%22zh_CN%22%2C%22_os_version%22%3A%229.0%22%2C%22_device%22%3A%22iPad3%2C4%22%2C%22_resolution%22%3A%221536x2048%22%7D
```

I see that OpenUDID is depregated - so I dont know if this is creating problems.
http://blog.appsfire.com/udid-is-dead-openudid-is-deprecated-long-live-advertisingidentifier/

I spent some time looking at solutions and saw that the "[CountlyDeviceInfo udid]" command is used by the sessions_started event just before this and it does return the device_id - it seems like there is a threading problem or something.

I also saw someone else having this problem suggest to simply get the Device ID once via [CountlyDeviceInfo udid] and then store it on the device and simply retrieve that value rather than generating it every time?

**Comment by erkanyildiz** [comment]
Hi @dieskim,

I still could not reproduce the issue. Does it crash/hang even if a correct UDID returned?

This only happens when [CountlyDeviceInfo udid] called in tokenSession method? Not on other points?

Can you send me a link for other people you mentioned having the same problem?

**Comment by dieskim** [comment]
@erkanyildiz - This issues was brought up by someone using the Titanium Module via a email sent to me from Gorkem. I have tested and have been able to reproduce this problem.

The app does not crash when correct UDID is returned.

When the app crashes - the correct UDID is returned via [CountlyDeviceInfo udid] in the sessions_started=1 event - then the UDID is requested again via [CountlyDeviceInfo udid] inside the tokenSession event. Here it then crashes and nothing else happens.

Have you tried to install the app - subscribe to push - then remove the app and install again and subscribe again? Repeating this process multiple times we see this problem.

Let me know what else I can do to help...

**Comment by erkanyildiz** [comment]
Can you provide me a link other people having the same issue with OpenUDID under Titanium/Appcelerator?

Do you have any clue what this dictionary might be:

{   
  "Create Time" = "464935993.428005";
   Expiry = inf;
  "HSTS Host" = 1;
  "Include Subdomains" = 1;
}

**Comment by dieskim** [comment]
There is not link - its an email thread that we have been having.

I have no idea what that dictionary might be - I sometimes got a different dictionary or some random values showing up in there...

**Comment by ILI4S** [comment]
@dieskim we ran into a similar crash and solved it by [using IDFA instead of OpenUDID](https://github.com/djz-code/countly-sdk-ios/commit/a961a7dc26ffd1321869968894a960fcff0725f3). 

I notified Countly about the crash nearly two months ago and this is the response I received:
```
We are aware of this issue and will fix it soon. Thanks for reporting. 
```

I'm kind of disappointed in Countly's lack of response, to be frank.

**Comment by dieskim** [comment]
@ILI4S - I was able to fix this in my Appcelerator Modules - see - https://github.com/dieskim/countly-sdk-appcelerator-titanium-ios/commit/9a1766a7f4713cf5fcf64be175c009cd3be8c6a4#diff-ce92678ac63d2da4a82cb541cabab676 - I basically stored the OUDID and retrieve it rather than generating it all the time...

**Comment by erkanyildiz** [comment]
It looks like this is a Titanium & OpenUDID combined issue.
We could not reproduce the issue on native test app. By the way, if you experience it anyway, using IDFA instead of OpenUDID by setting COUNTLY_PREFER_IDFA flag is the best solution.
Thanks.
