### ISSUE TITLE
recordUserDetails - NSURLConnection delegate thread problem

### ISSUE THREAD

**Issue by dieskim** [Countly/countly-sdk-ios#65]
I am having some problems with iOS SDK on Countly Enterprise Edition v15.08

Everything works fine until I run a Countly recordUserDetails

Normal events run like so:

[INFO] :   Request Started
[INFO] :    http://host.com/i?app_key=1a0ea80f9fbd51f457f76adfa5a614e6fc9da024&device_id=7a017c22435ef78d3fdbffd561c25f0a7a9b9c4e&timestamp=1444728697&events=%5B%7B%22key%22%3A%22keySegmentationCountSum%22%2C%22count%22%3A1%2C%22segmentation%22%3A%7B%22device%22%3A%22iPhone%204S%22%2C%22country%22%3A%22USA%22%7D%2C%22timestamp%22%3A1444728675%2C%22sum%22%3A0.99%7D%5D
[INFO] :   Request Completed

but when I run a recordUserDetails event the SDK NEVER receives the  [INFO] :   Request Completed message and no other events are sent

Events still get recorded but never get sent to the server - seems that the recordUserDetails request to the server just never completes and then it cant send any other events.

I have also tried sending less userinfo - ie only a name and it does the same. I also tried this on different apps - they all do the same thing.

[INFO] :   -[Countly recordUserDetails:]
[INFO] :   Extracted picturePath: /images/appicon.png
[INFO] :   picturePath: /images/appicon.png
[INFO] :   Request Started
[INFO] :    http://host.com/i?app_key=1a0ea80f9fbd51f457f76adfa5a614e6fc9da024&device_id=7a017c22435ef78d3fdbffd561c25f0a7a9b9c4e&timestamp=1444728720&sdk_version=15.06.01&user_details=%7B%22organization%22%3A%22testOrg%22%2C%22custom%22%3A%7B%22key2%22%3A%22value2%22%2C%22key1%22% 3A%22value1%22%7D%2C%22name%22%3A%22testName%22%2C%22phone%22%3A%22testPhone%22%2C%22gender%22%3A%22M%22%2C%22picture%22%3A%22https%3A%5C%2F%5C%2Fcount.ly%5C%2Fwp-content%5C%2Fuploads%5C%2F2014%5C%2F10%5C%2Flogo.png%22%2C%22email%22%3A%22testemail%40gmail.com%22%2C%22picturePath%22%3A%22%5C%2Fimages%5C%2Fappicon.png%22%2C%22byear%22%3A1980%2C%22username%22%3A%22testUsername%22%7D

Here is another example where I only sent the Custom Data key1 = value1 and key2 = value2

It also never receives the reply...

Custom Data sent:

[INFO] :   {
[INFO] :       custom =     {
[INFO] :           key1 = value1;
[INFO] :           key2 = value2;
[INFO] :       };
[INFO] :   } userDetails
[INFO] :   -[Countly recordUserDetails:]
[INFO] :   device_udid stored - no need to generate
[INFO] :   device_udid 7a017c22435ef78d3fdbffd561c25f0a7a9b9c4e
[INFO] :   Request Started
[INFO] :    http://host.com/i?app_key=1a0ea80f9fbd51f457f76adfa5a614e6fc9da024&device_id=7a017c22435ef78d3fdbffd561c25f0a7a9b9c4e&timestamp=1444729383&sdk_version=15.06.01&user_details=%7B%22custom%22%3A%7B%22key2%22%3A%22value2%22%2C%22key1%22%3A%22value1%22%7D%7D

I believe events like
[CountlyConnectionQueue.sharedInstance sendUserDetails];
[CountlyConnectionQueue sharedInstance] recordEvents:[eventQueue events]];

are initiated on a different thread than what the NSURLConnection delegates were created on? Then the connectionDidFinishLoading is never run as its on a different thread.

**Comment by dieskim** [comment]
For now I have come up with a TEMP fix 

It basically does the same as what is done with crash reports

https://github.com/dieskim/countly-sdk-ios/commit/0f2e33807d051b1255e9dcd13c06862e8c573a95

But I believe that if it fails 

```if (error || !recvData)```

it will cause all event sending to pause. I believe this will happen for crash and events as well.

**Comment by dieskim** [comment]
Also it seems that connectionWithRequest:delegate has been Deprecated in iOS 9.0.

https://developer.apple.com/library/prerelease/ios//documentation/Cocoa/Reference/Foundation/Classes/NSURLConnection_Class/index.html

**Comment by erkanyildiz** [comment]
Actually I have tried all these combinations. No problem at all.

# Picture existence
- none
- only kCLYUserPicture (on web)
- only kCLYUserPicturePath (on device)
- both kCLYUserPicture & kCLYUserPicturePath

# Picture file format 
- JPG
- PNG
- GIF

# Before / after recording other events

# Internet connection available / not available (sending later in next session)

# Real Device / simulator


Now I think this is a Titanium issue. 
Just like that Open-UDID problem.

**Comment by erkanyildiz** [comment]
Your temp fix has no good use. It is a special case where SDK sends a synchronous request for delivering crash report just before application is terminated. You must not use it for sending user details, as it will cause the app to be unresponsive while that request is going on, and it is impossible to upload profile picture that way.

**Comment by dieskim** [comment]
Ok I will look at what I can figure out - would you mind looking at my Temporary solution and letting me know if there is anything wrong with it or if I can use that as a Temporary solution for now? 

https://github.com/dieskim/countly-sdk-ios/commit/0f2e33807d051b1255e9dcd13c06862e8c573a95

**Comment by dieskim** [comment]
Simular issue - https://developer.appcelerator.com/question/122673/nsurlconnection-in-ios-module

**Comment by erkanyildiz** [comment]
Currently NSURLConnection deprecation in iOS9 is not a problem. We will be using NSURLSession instead of it in the future anyway.

**Comment by dieskim** [comment]
Ok I might have a solution - needs some more testing

https://developer.appcelerator.com/question/144514/module-development----nsurlrequest

Adding the following macro
```ENSURE_UI_THREAD```
Info the proxy function that calls recordUserDetails seems to fix it..

**Comment by erkanyildiz** [comment]
According to our tests with native app, this looks like a Titanium related issue.
