### ISSUE TITLE
iOS 9 deprecated methods

### ISSUE THREAD

**Issue by yoeriboven** [Countly/countly-sdk-ios#66]
The SDK gives some warnings on iOS 9.

- CFURLCreateStringByAddingPercentEscapes
- stringByReplacingPercentEscapesUsingEncoding:
- connectionWithRequest:delegate:
- UIAlertView
- sendSynchronousRequest:returningResponse:error:

All are deprecated.

**Comment by erkanyildiz** [comment]
They will be gone when this branch is merged: 
https://github.com/erkanyildiz/countly-sdk-ios/tree/persistency

Thank you.
