### ISSUE TITLE
tvOS Support

### ISSUE THREAD

**Issue by kingsapo** [Countly/countly-sdk-ios#67]
SDK will not compile under tvOS target. Are there any plans to add support for it?

**Comment by gorkem-cetin** [comment]
We do and will work on it, but cannot give a specific time estimate for this. But shouldnt wait too long.

**Comment by erkanyildiz** [comment]
It is here for now:
https://github.com/erkanyildiz/countly-sdk-ios/tree/apm

When the new version of the SDK is ready to be released it will be merged.
