### ISSUE TITLE
recordUserDetails should have it's counterpart to safely update custom properties

### ISSUE THREAD

**Issue by garnett** [Countly/countly-sdk-ios#69]
SDK should allow to query current user details
`- (NSDictionary *)currentUserDetails`

Use case for that:
1. I'm setting custom property on user upon initialization:
`[[Countly sharedInstance] recordUserDetails:@{kCLYUserCustom: @{@"prop": @1}}]`
2. Then in completely different part of the app I want to set another property:
`[[Countly sharedInstance] recordUserDetails:@{kCLYUserCustom: @{@"prop2": @"another"}}]`

Which apparently wipes my first property.

Proposed approach is to query `currentUserDetails` and update this collection as necessary, then perform
`[[Countly sharedInstance] recordUserDetails:adjustedUserDetails]`

Another possible solution is to iterate `kCLYUserCustom` inside SDK and update keys in the same fashion as predefined keys (e.g. name or birthday) -- checking if they are non-nil before updating.

Would be happy to make PR, just let me know what approach is preferred.

**Comment by erkanyildiz** [comment]
Hello,

I will make sure the new SDK follows these new rules about user details soon:
http://resources.count.ly/docs/sdk-development-guide#section-user-details

push and pushUnique methods on pseudo code should be ok, right?

**Comment by garnett** [comment]
@erkanyildiz Documentation still looks not very obvious for me, sorry. Just to confirm:

`Countly.userData.push(string key, string value)` is going to append user properties
`Countly.userData.pushUnique(string key, string value)` is going to replace particular user property

is that correct?

**Comment by ar2rsawseen** [comment]
@garnett those two methods you listed will be used for custom properties and they will create an array property with many possible values, in first situation with possible duplicatevalues in second only with unique values

**Comment by garnett** [comment]
I see, thanks @ar2rsawseen. Is there any approximate estimation of rolling this changes out?

**Comment by erkanyildiz** [comment]
We can say within this month.

**Comment by erkanyildiz** [comment]
This commit solves it: f2ac81f6bd04183bb2be07fd031f95d1849114d2

Soon we will merge.
