### ISSUE TITLE
Release 16.02 won't compile (missing header)

### ISSUE THREAD

**Issue by Rool** [Countly/countly-sdk-ios#75]
The latest 16.02 release did not compile when I installed the latest pod.
The compile error is:
> Pods/Countly/CountlyAPM.h:25:31: Unknown type name 'CountlyAPMNetworkLog' Pods/Countly/CountlyAPM.h:58:31: Unknown type name 'CountlyAPMNetworkLog'

It seems the #import CountlyAPMNetworkLog.h is missing in CountlyAPM.h

I also get an eror in CounlyCommon.h, complaining about #include <execinfo.h> and <ifaddrs.h> with the message: 

> Pods/Countly/CountlyCommon.h:60:10: Include of non-modular header inside framework module 'Countly.CountlyCommon'
Pods/Countly/CountlyCommon.h:64:9: Include of non-modular header inside framework module 'Countly.CountlyCommon'

This occurred with cocoapod 1.0.0.beta3 and beta4, Xcode 7.2.1

**Comment by erkanyildiz** [comment]
Just tried with CocoaPods 0.39.0, works without any issues.

It looks like CocoaPods beta issue.

**Comment by rad182** [comment]
I also have this problem. using CocoaPods 1.0.0
