### ISSUE TITLE
Pod not usable from Swift

### ISSUE THREAD

**Issue by appcoders** [Countly/countly-sdk-ios#77]
Please add

`  s.public_header_files = 'Countly.h', 'CountlyUserDetails.h', 'CountlyConfig.h', 'CountlyCrashReporter.h'`

to the spec so that it works from Swift also.

Kind regards,
Markus

**Comment by erkanyildiz** [comment]
Thanks for informing us.
I will take care of this one.

**Comment by erkanyildiz** [comment]
Hi again, 

This one on my fork fixes it:
https://github.com/erkanyildiz/countly-sdk-ios/commit/c1baabf55e43ef251727d636c6d35be4777ca549

It will be merged to main when all is finished. Thanks again.
