### ISSUE TITLE
sharedApplication is unavailable in iOS extension

### ISSUE THREAD

**Issue by ddaddy** [Countly/countly-sdk-ios#78]
I am updating an old project that has both an Today Widget extension and also a WatchKit v1 extension.

I get a compiler error in CountlyDeviceInfo.m on line 385 in this method
```
+ (BOOL)isInBackground
{
#if TARGET_OS_IOS
    return UIApplication.sharedApplication.applicationState == UIApplicationStateBackground;
#else
    return NO;
#endif
}
```

saying `sharedApplication` is unavailable.

**Comment by erkanyildiz** [comment]
WatchKit v1 is not supported anymore.

And for Today Extension I will check and update the code.
For now, you can check if TARGET_IS_EXTENSION and return NO directly.

Thank you.

**Comment by ddaddy** [comment]
Thanks.
FYI, after fixing that, there's many more errors for an extension.
eg. `UIAlertView` `initWithTitle` not available in Countly.m
`sharedApplication` `openURL`

**Comment by erkanyildiz** [comment]
I know, they are related to Push Notifications. Update for Push Notifications is in progress. When it is finished, this will be fixed too.

**Comment by jboehle** [comment]
When are these fixes for using Countly in an extension going to be made available?

**Comment by jboehle** [comment]
Using TARGET_IS_EXTENSION will not work if Countly is being compiled into a shared library/framework with APPLICATION_EXTENSION_API_ONLY turned on. For that it looks like the best solution is for Countly to use a preprocessor define, say COUNTLY_EXTENSION_API_ONLY, or something along those lines, that can be added to the preprocessor defines for the project that has both Countly and APPLICATION_EXTENSION_API_ONLY=YES.

**Comment by jboehle** [comment]
Looked into it a little more. Sorry for my confusing comment above. I thought TARGET_IS_EXTENSION was something Xcode was providing automatically for Extension targets. It looks like instead, it's just a custom preprocessor define added to a project. So, I would still suggest using a define named specific to Countly. Instead of something generic like TARGET_IS_EXTENSION, maybe COUNTLY_IS_EXTENSION?

**Comment by erkanyildiz** [comment]
For now, we do not support Today Extensions.
As soon as we find some more time, we will add support for Today Extensions.

We already have this enhancement on our backlog. 
So closing this, as no need to keep it as an issue here.

**Comment by VictorSharov** [comment]
I will wait this ability too, thanks
