### ISSUE TITLE
Countly APM(CLYAPM) conflict with AFNetworking.

### ISSUE THREAD

**Issue by iineva** [Countly/countly-sdk-ios#82]
Versions:
- AFNetworking: 3.1.0
- Countly: 16.02
- Tested iOS Version: 9.3.1(Simulator and iPhone 6), 8.4(Simulator only)

When I open `CLYAPM` and request HTTP use AFNetworking, I got nothing.

```
    CountlyConfig* config = [[CountlyConfig alloc] init];
    config.appKey = @"bba97f2234731c3586b70e6f56641c308893260f";
    config.host = @"http://countly.ineva.cn";

// AFNetworking error:
    config.features = @[CLYMessaging, CLYCrashReporting, CLYAPM, CLYViewTracking];

//  AFNetworking works:
//    config.features = @[CLYMessaging, CLYCrashReporting, CLYViewTracking];

    config.launchOptions = launchOptions;
    config.forceDeviceIDInitialization = YES;
    config.updateSessionPeriod = DEBUG ? 3 : 60 * 5;
    [Countly.sharedInstance startWithConfig:config];
```

**Comment by erkanyildiz** [comment]
Thanks for reporting. 
Actually it is an already known issue and still in my to do list.
Soon, I will be working on it again.

**Comment by FengZhiZhang** [comment]
dear sir ：
        I had the same problem too . Do you have any good idea ?

**Comment by erkanyildiz** [comment]
On v16.12 this APM issue is partially fixed. 
But APM feature is temporarily disabled until server completely supports it.
When it is ready to roll, I will share info here again.
