### ISSUE TITLE
Countly 16.02 Broken in CocoaPods 1.0.0 

### ISSUE THREAD

**Issue by rad182** [Countly/countly-sdk-ios#86]
I get this error when trying to add "import Countly" in my Swift Project
<img width="253" alt="screen shot 2016-05-23 at 11 02 12 am" src="https://cloud.githubusercontent.com/assets/71201/15459250/eb943198-20d5-11e6-8c7f-5d8410835f22.png">
Also tried to add in Bridging Header to test my luck but got "Could not build module 'Countly'" Error

**Comment by erkanyildiz** [comment]
Fixed in 16.02.01, please use it 

https://github.com/Countly/countly-sdk-ios/releases/tag/16.02.01

**Comment by rad182** [comment]
@erkanyildiz thanks but it's not yet available in the CocoaPod specs repo?

**Comment by erkanyildiz** [comment]
No, it is available:
https://cocoapods.org/?q=countly

**Comment by rad182** [comment]
sorry my bad. I needed to `pod repo update` thanks @erkanyildiz

**Comment by erkanyildiz** [comment]
You are welcome.
