### ISSUE TITLE
Fix iOS 9 Deprecation Warnings

### ISSUE THREAD

**Issue by jllubia** [Countly/countly-sdk-ios#94]
Countly uses ```UIAlertView``` and ```[NSURLConnection sendSynchronousRequest:returningResponse:error:]``` which were deprecated with iOS 9.

![screen shot 2016-08-19 at 16 20 59](https://cloud.githubusercontent.com/assets/814630/17812804/f1bfefba-6628-11e6-9af6-fe0651eb9d37.png)

**Comment by erkanyildiz** [comment]
We already know this, thanks for reporting.

They will be gone when this is merged: https://github.com/erkanyildiz/countly-sdk-ios/tree/pushnotifications

Thanks again.
