### ISSUE TITLE
redefinition of macro TARGET_OS_OSX

### ISSUE THREAD

**Issue by jboehle-quotient** [Countly/countly-sdk-ios#95]
When built under Xcode 8, I am getting the following compilation error:

In file included from /Users/jboehle/Desktop/projects/ios/libexternal/Countly/Countly.m:9:
/Users/jboehle/Desktop/projects/ios/libexternal/Countly/CountlyCommon.h:50:9: error: 'TARGET_OS_OSX' macro redefined [-Werror,-Wmacro-redefined]
#define TARGET_OS_OSX (!(TARGET_OS_IOS || TARGET_OS_TV || TARGET_OS_WATCH))
        ^
In module 'Foundation' imported from /Users/jboehle/Desktop/projects/ios/libexternal/Countly/CountlyCommon.h:7:
In module 'CoreFoundation' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.0.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:6:
In module 'Darwin' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.0.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:16:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.0.sdk/usr/include/TargetConditionals.h:98:13: note: previous definition is here
    #define TARGET_OS_OSX               0
            ^
1 error generated.

**Comment by erkanyildiz** [comment]
Thanks for reporting, it is already fixed here:
https://github.com/erkanyildiz/countly-sdk-ios/commit/b13afa5fd51873e47bbe809a3913cfa3022de3a9

It will be merged soon.
